//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CAM.Views.CampanhaCopia.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CAM.Views.CampanhaCopia.App_LocalResources.UIResourc" +
                            "e", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclos Letivos.
        /// </summary>
        public static string CiclosLetivosCampanhaDestino_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("CiclosLetivosCampanhaDestino_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Campanha.
        /// </summary>
        public static string CopiarCampanha_Title {
            get {
                return ResourceManager.GetString("CopiarCampanha_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas.
        /// </summary>
        public static string EtapasGPI_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EtapasGPI_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha.
        /// </summary>
        public static string fieldsetCampanha_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCampanha_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha.
        /// </summary>
        public static string fieldsetCampanhaConfirmacao_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCampanhaConfirmacao_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string fieldsetCampanhaDestino_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCampanhaDestino_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        public static string fieldsetCampanhaOrigem_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCampanhaOrigem_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas da campanha.
        /// </summary>
        public static string fieldsetOfertaConfirmacao_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetOfertaConfirmacao_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo GPI.
        /// </summary>
        public static string fieldsetProcessoGPI_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetProcessoGPI_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo de seleção regular.
        /// </summary>
        public static string fieldsetProcessoSelecaoRegular_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetProcessoSelecaoRegular_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos seletivos.
        /// </summary>
        public static string fieldsetProcessoSeletivoConfirmacao_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetProcessoSeletivoConfirmacao_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        public static string gridCampanhaOferta_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridCampanhaOferta_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas da campanha.
        /// </summary>
        public static string gridCampanhaOfertaConfirmacao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridCampanhaOfertaConfirmacao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos Seletivos.
        /// </summary>
        public static string gridProcessoSeletivo_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridProcessoSeletivo_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione as convocações que deseja copiar..
        /// </summary>
        public static string MSG_Copia_Campanha_Convocacao {
            get {
                return ResourceManager.GetString("MSG_Copia_Campanha_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os processos do GPI que deseja copiar..
        /// </summary>
        public static string MSG_Copia_Campanha_Processo_GPI {
            get {
                return ResourceManager.GetString("MSG_Copia_Campanha_Processo_GPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione as ofertas que deseja copiar..
        /// </summary>
        public static string MSG_Copia_Campanha_Selecao_Oferta {
            get {
                return ResourceManager.GetString("MSG_Copia_Campanha_Selecao_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importante: ofertas do tipo &quot;turma&quot; não poderão ser copiadas..
        /// </summary>
        public static string MSG_Copia_Campanha_Selecao_Oferta_Mensagem {
            get {
                return ResourceManager.GetString("MSG_Copia_Campanha_Selecao_Oferta_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os processos seletivos que deseja copiar..
        /// </summary>
        public static string MSG_Copia_Campanha_Selecao_ProcessoSeletivo {
            get {
                return ResourceManager.GetString("MSG_Copia_Campanha_Selecao_ProcessoSeletivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha copiada com sucesso..
        /// </summary>
        public static string MSG_CopiaCampanha_Sucesso {
            get {
                return ResourceManager.GetString("MSG_CopiaCampanha_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este processo seletivo não possui processo de inscrição do GPI associado..
        /// </summary>
        public static string MSG_Mensagem_Vinculo_Gpi {
            get {
                return ResourceManager.GetString("MSG_Mensagem_Vinculo_Gpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string MSG_Titulo_Erro {
            get {
                return ResourceManager.GetString("MSG_Titulo_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string MSG_Titulo_Sucesso {
            get {
                return ResourceManager.GetString("MSG_Titulo_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepCampanha {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepCampanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepCampanha_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepCampanha_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepConfirmacao {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepConfirmacao_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepConfirmacao_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocação.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepConvocacao {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepConvocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocação.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepConvocacao_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepConvocacao_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas da Campanha.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepOferta {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas da Campanha.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepOferta_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepOferta_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo GPI.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepProcessoGPI {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepProcessoGPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo GPI.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepProcessoGPI_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepProcessoGPI_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos Seletivos.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepProcessoSeletivo {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepProcessoSeletivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos Seletivos.
        /// </summary>
        public static string Wizard_CopiarCampanha_StepProcessoSeletivo_Funcionalidade {
            get {
                return ResourceManager.GetString("Wizard_CopiarCampanha_StepProcessoSeletivo_Funcionalidade", resourceCulture);
            }
        }
    }
}
