#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Academico.Common.Constants;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Academico.UI.Mvc.Areas.CAM.Lookups;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Framework;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Framework.Model;
    
    #line default
    #line hidden
    using SMC.Framework.Security;
    
    #line 3 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Framework.UI.Mvc;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    using SMC.Framework.UI.Mvc.Html;
    
    #line default
    #line hidden
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CAM/Lookups/LK_CAM_003_SelecaoOfertaCampanha/Views/CustomOfertaCampanhaLi" +
        "staLookup.cshtml")]
    public partial class _Areas_CAM_Lookups_LK_CAM_003_SelecaoOfertaCampanha_Views_CustomOfertaCampanhaListaLookup_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMCPagerModel<object>>
    {
        public _Areas_CAM_Lookups_LK_CAM_003_SelecaoOfertaCampanha_Views_CustomOfertaCampanhaListaLookup_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" id=\"gridListarOfertaCampanhaWrapper\"");

WriteLiteral(" data-detail-property=\"model\"");

WriteLiteral(")>\r\n    \r\n");

            
            #line 12 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
     if (Model != null && Model.Count > 0)
    {
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
          
            var token = (Model.FirstOrDefault() as SelecaoOfertaCampanhaLookupListaViewModel).TipoOfertaToken;
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
                
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    Write(Smc.Grid("gridListarOfertaCampanhaLookup"
            , new SMCPagerModel<SelecaoOfertaCampanhaLookupListaViewModel>(Model))
                .HideNavigator()
                .HidePager()
                .HideRowNumber()
                .HideRowsTotalizer()
                .HideGridTitle()
                .AllowSelect(a => a.Seq, singleSelect: false)
                .FieldColumn(x => x.CursoOferta, visible: token != TOKEN_TIPO_OFERTA.TURMA)
                .FieldColumn(x => x.Localidade, visible: token != TOKEN_TIPO_OFERTA.TURMA)
                .FieldColumn(x => x.Turno, visible: token != TOKEN_TIPO_OFERTA.TURMA)
                .FieldColumn(x => x.AreaConcentracao, visible: token == TOKEN_TIPO_OFERTA.LINHA_PESQUISA || token == TOKEN_TIPO_OFERTA.EIXO_TEMATICO || token == TOKEN_TIPO_OFERTA.AREA_CONCENTRACAO)
                .FieldColumn(x => x.AreaTematica, visible: token == TOKEN_TIPO_OFERTA.AREA_TEMATICA)
                .FieldColumn(x => x.LinhaPesquisa, visible: token == TOKEN_TIPO_OFERTA.LINHA_PESQUISA || token == TOKEN_TIPO_OFERTA.EIXO_TEMATICO)
                .FieldColumn(x => x.EixoTematico, visible: token == TOKEN_TIPO_OFERTA.EIXO_TEMATICO)
                .FieldColumn(x => x.Orientador, visible: token == TOKEN_TIPO_OFERTA.ORIENTADOR)
                .FieldColumn(x => x.Turma, visible: token == TOKEN_TIPO_OFERTA.TURMA)
                .Attribute("data-detail-property", SMCLookupHelper.GetCurrentPropertyName(Smc))
                .Attribute("data-default", "true")
        );

            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
         
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral("><i>Nenhum registro foi encontrado.</i></p>\r\n");

            
            #line 41 "..\..\Areas\CAM\Lookups\LK_CAM_003_SelecaoOfertaCampanha\Views\CustomOfertaCampanhaListaLookup.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
