//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.SRC.Views.Servico.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.SRC.Views.Servico.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar processos.
        /// </summary>
        public static string botao_consultar_processos {
            get {
                return ResourceManager.GetString("botao_consultar_processos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar processos.
        /// </summary>
        public static string botao_consultar_processos_tooltip {
            get {
                return ResourceManager.GetString("botao_consultar_processos_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar taxas x núcleo.
        /// </summary>
        public static string botao_consultar_taxas_nucleo {
            get {
                return ResourceManager.GetString("botao_consultar_taxas_nucleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de taxas x núcleo.
        /// </summary>
        public static string Botao_Consultar_Taxas_Nucleo_Title {
            get {
                return ResourceManager.GetString("Botao_Consultar_Taxas_Nucleo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar taxas x núcleo.
        /// </summary>
        public static string botao_consultar_taxas_nucleo_tooltip {
            get {
                return ResourceManager.GetString("botao_consultar_taxas_nucleo_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string botao_edit_servico_tooltip {
            get {
                return ResourceManager.GetString("botao_edit_servico_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string botao_excluir_servico_tooltip {
            get {
                return ResourceManager.GetString("botao_excluir_servico_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Botao_Fechar {
            get {
                return ResourceManager.GetString("Botao_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Serviço.
        /// </summary>
        public static string Botao_Incluir_Novo_Servico {
            get {
                return ResourceManager.GetString("Botao_Incluir_Novo_Servico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência.
        /// </summary>
        public static string Confirmacao_Agencia {
            get {
                return ResourceManager.GetString("Confirmacao_Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string Confirmacao_Banco {
            get {
                return ResourceManager.GetString("Confirmacao_Banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira.
        /// </summary>
        public static string Confirmacao_Carteira {
            get {
                return ResourceManager.GetString("Confirmacao_Carteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string Confirmacao_Conta {
            get {
                return ResourceManager.GetString("Confirmacao_Conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Serviço.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do serviço &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Servico_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Servico_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Serviço.
        /// </summary>
        public static string Exclusao_Servico_Title {
            get {
                return ResourceManager.GetString("Exclusao_Servico_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Gerais.
        /// </summary>
        public static string fieldset_cadastro_geral {
            get {
                return ResourceManager.GetString("fieldset_cadastro_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas Template SGF.
        /// </summary>
        public static string fieldset_descricao_etapas_sgf {
            get {
                return ResourceManager.GetString("fieldset_descricao_etapas_sgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Níveis de ensino x Tipo de Vínculo.
        /// </summary>
        public static string fieldset_nivel_ensino_tipo_vinculo {
            get {
                return ResourceManager.GetString("fieldset_nivel_ensino_tipo_vinculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações e Restrições.
        /// </summary>
        public static string fieldset_situacoes_restricoes {
            get {
                return ResourceManager.GetString("fieldset_situacoes_restricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string fieldset_taxas {
            get {
                return ResourceManager.GetString("fieldset_taxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de notificação para etapas.
        /// </summary>
        public static string fieldset_tipos_notificacao_para_etapas {
            get {
                return ResourceManager.GetString("fieldset_tipos_notificacao_para_etapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string gridServico_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridServico_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Serviço.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Serviço.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Níveis de Ensino x Tipo de Vínculo que permitem solicitar o serviço.
        /// </summary>
        public static string InstituicaoNivelServicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("InstituicaoNivelServicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Níveis de Ensino x Tipo de Vínculo que permitem solicitar o serviço.
        /// </summary>
        public static string InstituicaoNivelServicosSemTipoTransacao_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("InstituicaoNivelServicosSemTipoTransacao_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativas.
        /// </summary>
        public static string Justificativas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Justificativas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço excluído com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Exclusao_Servico {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Exclusao_Servico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço salvo com sucesso..
        /// </summary>
        public static string Mensagem_Sucesso_Servico {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Servico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivos de bloqueio para parcelas.
        /// </summary>
        public static string MotivosBloqueioParcela_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("MotivosBloqueioParcela_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção. Foi identificado que não há parametrização de valor por núcleo no sistema financeiro para as seguintes entidades x taxas:
        ///&lt;br /&gt;
        ///{0}
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Confirma a associação?  
        ///.
        /// </summary>
        public static string MSG_Assert_ProximoPassoTaxa {
            get {
                return ResourceManager.GetString("MSG_Assert_ProximoPassoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração de taxa permitida somente quando o parâmetro &quot;Integração Financeira&quot; foi marcado na aba Dados Gerais como: &quot;Cobrança de Taxa&quot;.
        /// </summary>
        public static string MSG_ConfiguracaoTaxaNaoPermitida {
            get {
                return ResourceManager.GetString("MSG_ConfiguracaoTaxaNaoPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção. Não foi identificado no sistema financeiro parametrização dos valores para:
        ///&lt;br /&gt;
        ///{0}.
        /// </summary>
        public static string MSG_ProximoPassoTaxa {
            get {
                return ResourceManager.GetString("MSG_ProximoPassoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrização de emissão.
        /// </summary>
        public static string ParametrosEmissaoTaxa_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ParametrosEmissaoTaxa_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrização de emissão.
        /// </summary>
        public static string ParametrosEmissaoTaxaSemCamposEmissao_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ParametrosEmissaoTaxaSemCamposEmissao_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrição entre serviços.
        /// </summary>
        public static string RestricoesSolicitacaoSimultanea_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("RestricoesSolicitacaoSimultanea_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações para atendimento do serviço.
        /// </summary>
        public static string SituacoesAtender_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("SituacoesAtender_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações para reabertura do serviço.
        /// </summary>
        public static string SituacoesReabrir_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("SituacoesReabrir_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações para abertura do serviço.
        /// </summary>
        public static string SituacoesSolicitar_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("SituacoesSolicitar_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string Taxas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Taxas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Documento.
        /// </summary>
        public static string TiposDocumento_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("TiposDocumento_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de notificação para etapas.
        /// </summary>
        public static string TiposNotificacao_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("TiposNotificacao_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Gerais.
        /// </summary>
        public static string WizardStepCadastroGeral_Title {
            get {
                return ResourceManager.GetString("WizardStepCadastroGeral_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Níveis de ensino x Tipo de Vínculo.
        /// </summary>
        public static string WizardStepNivelEnsinoTipoVinculo_Title {
            get {
                return ResourceManager.GetString("WizardStepNivelEnsinoTipoVinculo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string WizardStepServicoConfirmacao_Title {
            get {
                return ResourceManager.GetString("WizardStepServicoConfirmacao_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações e Restrições.
        /// </summary>
        public static string WizardStepSituacoesResticoes_Title {
            get {
                return ResourceManager.GetString("WizardStepSituacoesResticoes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas .
        /// </summary>
        public static string WizardStepTaxas_Title {
            get {
                return ResourceManager.GetString("WizardStepTaxas_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de notificação para etapas.
        /// </summary>
        public static string WizardStepTiposNotificacaoParaEtapas_Title {
            get {
                return ResourceManager.GetString("WizardStepTiposNotificacaoParaEtapas_Title", resourceCulture);
            }
        }
    }
}
