using System.CodeDom;

namespace SMC.Academico.Common.Areas.SRC.Constants
{
    public static class TOKEN_SOLICITACAO_SERVICO
    {
        /*********************** **************** ***********************/
        /*********************** REQUER VALIDAÇÃO ***********************/
        /*********************** **************** ***********************/
        public const string SELECAO_TURMA_MATRICULA = "SELECAO_TURMA_MATRICULA";
        public const string DISCIPLINA_ELETIVA = "SOLICITACAO_INCLUSAO_DISCIPLINA_ELETIVA";
        public const string ALTERACAO_PLANO_ESTUDO = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO";
        public const string ALTERACAO_PLANO_ESTUDO_DI = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA";
        public const string SELECAO_ATIVIDADE_ACADEMICA_MATRICULA = "SELECAO_ATIVIDADE_ACADEMICA_MATRICULA";
        public const string CONFIRMACAO_SOLICITACAO_MATRICULA = "CONFIRMACAO_SOLICITACAO_MATRICULA";
        public const string INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA = "INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA";
        public const string CHANCELA_PLANO_ESTUDO = "CHANCELA_PLANO_ESTUDO";
        public const string REGISTRO_DOCUMENTO_ENTREGUE = "REGISTRO_DOCUMENTO_ENTREGUE";
        public const string CONFIRMACAO_SELECAO_TURMA = "CONFIRMACAO_SELECAO_TURMA";
        public const string CONFIRMACAO_SELECAO_ATIVIDADE_ACADEMICA = "CONFIRMACAO_SELECAO_ATIVIDADE_ACADEMICA";
        public const string CONCLUSAO_MATRICULA = "CONCLUSAO_MATRICULA";
        public const string EFETIVACAO_SELECAO_TURMAS_INSTRUCOES = "INSTRUCOES";
        public const string REGISTRO_ENTREGA_DOCUMENTACAO_LATO_SENSU = "REGISTRO_ENTREGA_DOCUMENTACAO_LATO_SENSU";
        public const string SELECAO_COMPONENTE_CURRICULAR = "SELECAO_COMPONENTE_CURRICULAR";

        // tokens das seções das páginas
        public const string INSTRUCOES_SELECAO_ATIVIDADE = "INSTRUCOES";
        public const string INSTRUCOES_SELECAO_TURMA = "INSTRUCOES";
        public const string SECAO_TEXTO_CONFIRMACAO_MATRICULA = "SECAO_TEXTO_CONFIRMACAO_MATRICULA";
        public const string SECAO_TEXTO_INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA = "SECAO_TEXTO_INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA";
        public const string SECAO_TEXTO_PARECER_ENTREGA_DOCUMENTACAO = "SECAO_TEXTO_PARECER_ENTREGA_DOCUMENTACAO";
        public const string INSTRUCOES_CHANCELA = "INSTRUCOES";
        public const string INSTRUCOES = "INSTRUCOES";

        /*********************** ********* ***********************/
        /*********************** REVISADOS ***********************/
        /*********************** ********* ***********************/

        // Tokens das páginas

        public const string SOLICITACAO_PADRAO_SOLICITACAO_INSTRUCOES_INICIAIS = "SOLICITACAO_INSTRUCOES_INICIAIS";
        public const string SOLICITACAO_PADRAO_SOLICITACAO_FORMULARIO = "SOLICITACAO_FORMULARIO";
        public const string SOLICITACAO_PADRAO_SOLICITACAO_CONFIRMACAO = "SOLICITACAO_CONFIRMACAO";
        public const string SOLICITACAO_PADRAO_SOLICITACAO_INSTRUCOES_FINAIS = "SOLICITACAO_INSTRUCOES_FINAIS";
        public const string SOLICITACAO_PADRAO_SOLICITACAO_UPLOAD_DOCUMENTO = "SOLICITACAO_UPLOAD_DOCUMENTO";
        public const string SOLICITACAO_COBRANCA_TAXA = "SOLICITACAO_COBRANCA_TAXA";
        public const string ENTREGA_DOCUMENTO_DIGITAL = "ENTREGA_DOCUMENTO_DIGITAL";
        public const string DOWNLOAD_DOCUMENTO_DIGITAL = "DOWNLOAD_DOCUMENTO_DIGITAL";

        public const string ATENDIMENTO_PADRAO_ATENDIMENTO_DADOS_SOLICITACAO_ANEXO = "ATENDIMENTO_DADOS_SOLICITACAO_ANEXO";
        public const string ATENDIMENTO_PADRAO_ATENDIMENTO_PARECER = "ATENDIMENTO_PARECER";
        
        public const string SOLICITACAO_DISPENSA_ITENS_SEREM_DISPENSADOS = "SOLICITACAO_DISPENSA_ITENS_SEREM_DISPENSADOS";
        public const string SOLICITACAO_DISPENSA_ITENS_CURSADOS = "SOLICITACAO_DISPENSA_ITENS_CURSADOS";
        public const string SOLICITACAO_DISPENSA_AGRUPAMENTO_ITENS = "SOLICITACAO_DISPENSA_AGRUPAMENTO_ITENS";
        public const string ANALISE_EMISSAO_DOCUMENTO_CONCLUSAO = "ANALISE_EMISSAO_DOCUMENTO_CONCLUSAO";
        public const string PARECER_IMPRESSAO_DOCUMENTO = "PARECER_IMPRESSAO_DOCUMENTO";
        public const string ASSINATURA_REGISTRO_DOCUMENTO = "ASSINATURA_REGISTRO_DOCUMENTO";

        public const string ATENDIMENTO_PADRAO_ATENDIMENTO_REABERTURA = "ATENDIMENTO_REABERTURA";

        public const string ATENDIMENTO_PADRAO_ATENDIMENTO_INTERCAMBIO = "ATENDIMENTO_INTERCAMBIO";
        public const string PARECER_ENTREGA_DOCUMENTACAO = "PARECER_ENTREGA_DOCUMENTACAO";

        // Tokens das seções das páginas

        /*SOLICITACAO_INSTRUCOES_INICIAIS*/
        public const string SECAO_TEXTO_INSTRUCOES_INICIAIS = "SECAO_TEXTO_INSTRUCOES_INICIAIS";
        public const string SECAO_ARQUIVO_INSTRUCOES_INICIAIS = "SECAO_ARQUIVO_INSTRUCOES_INICIAIS";

        /*SOLICITACAO_FORMULARIO*/
        public const string SECAO_TEXTO_FORMULARIO = "SECAO_TEXTO_FORMULARIO";
        public const string SECAO_ARQUIVO_FORMULARIO = "SECAO_ARQUIVO_FORMULARIO";

        /*SOLICITACAO_UPLOAD_DOCUMENTO*/
        public const string SECAO_TEXTO_UPLOAD = "SECAO_TEXTO_UPLOAD";
        public const string SECAO_ARQUIVO_UPLOAD = "SECAO_ARQUIVO_UPLOAD";

        /*SOLICITACAO_CONFIRMACAO*/
        public const string SECAO_TEXTO_CONFIRMACAO = "SECAO_TEXTO_CONFIRMACAO";
        public const string SECAO_ARQUIVO_CONFIRMACAO = "SECAO_ARQUIVO_CONFIRMACAO";

        /*SOLICITACAO_INSTRUCOES_FINAIS*/
        public const string SECAO_TEXTO_INSTRUCOES_FINAIS = "SECAO_TEXTO_INSTRUCOES_FINAIS";
        public const string SECAO_ARQUIVO_INSTRUCOES_FINAIS = "SECAO_ARQUIVO_INSTRUCOES_FINAIS";

        /*ENTREGA_DOCUMENTO_DIGITAL*/
        public const string SECAO_TEXTO_ENTREGA_DOCUMENTO_DIGITAL = "SECAO_TEXTO_ENTREGA_DOCUMENTO_DIGITAL";

        /*DOWNLOAD_DOCUMENTO_DIGITAL*/
        public const string SECAO_TEXTO_DOWNLOAD_DOCUMENTO_DIGITAL = "SECAO_TEXTO_DOWNLOAD_DOCUMENTO_DIGITAL";

        /*ATENDIMENTO_DADOS_SOLICITACAO_ANEXO*/
        public const string SECAO_TEXTO_ATENDIMENTO_DADOS_SOLICITACAO = "SECAO_TEXTO_ATENDIMENTO_DADOS_SOLICITACAO";

        /*ATENDIMENTO_PARECER*/
        public const string SECAO_TEXTO_ATENDIMENTO_PARECER = "SECAO_TEXTO_ATENDIMENTO_PARECER";

        /*ATENDIMENTO_REABERTURA*/
        public const string SECAO_TEXTO_ATENDIMENTO_REABERTURA = "SECAO_TEXTO_ATENDIMENTO_REABERTURA";

        /*DOCUMENTO_CONCLUSAO*/
        public const string SECAO_TEXTO_ANALISE_EMISSAO_DOCUMENTO = "SECAO_TEXTO_ANALISE_EMISSAO_DOCUMENTO";
        public const string SECAO_TEXTO_PARECER_IMPRESSAO_DOCUMENTO = "SECAO_TEXTO_PARECER_IMPRESSAO_DOCUMENTO";
        public const string SECAO_TEXTO_ASSINATURA_REGISTRO_DOCUMENTO = "SECAO_TEXTO_ASSINATURA_REGISTRO_DOCUMENTO";
        public const string SECAO_TEXTO_ENTREGA_DOCUMENTO = "SECAO_TEXTO_ENTREGA_DOCUMENTO";


        /* SOLICITACAO_ATIVIDADE_COMPLEMENTAR */
        public const string SOLICITACAO_ATIVIDADE_COMPLEMENTAR = "SOLICITACAO_ATIVIDADE_COMPLEMENTAR";

        /* Dispensa */
        public const string SECAO_TEXTO_DISPENSA_ITENS_CURSADOS = "SECAO_TEXTO_DISPENSA_ITENS_CURSADOS";
        public const string SECAO_TEXTO_DISPENSA_ITENS_SEREM_DISPENSADOS = "SECAO_TEXTO_DISPENSA_ITENS_SEREM_DISPENSADOS";

        /*SOLICITACAO_COBRANCA_TAXA*/
        public const string SECAO_TEXTO_COBRANCA_TAXA_SERVICO = "SECAO_TEXTO_COBRANCA_TAXA_SERVICO";
    }
}