namespace SMC.Academico.Common.Areas.SRC.Constants
{
    public static class TOKEN_SERVICO
    {
        public const string ATIVIDADE_COMPLEMENTAR = "ATIVIDADE_COMPLEMENTAR";
        public const string CANCELAMENTO_MATRICULA = "CANCELAMENTO_MATRICULA";
        public const string DISPENSA_INDIVIDUAL = "DISPENSA_INDIVIDUAL";
        public const string MATRICULA_REABERTURA = "MATRICULA_REABERTURA";
        public const string MATRICULA_INGRESSANTE_GRADUACAO = "MATRICULA_INGRESSANTE_GRADUACAO";
        public const string TRANSFERENCIA_INTERNA_GRADUACAO = "TRANSFERENCIA_INTERNA_GRADUACAO";
        public const string MATRICULA_INGRESSANTE_DISCIPLINA_ISOLADA_GRADUACAO = "MATRICULA_INGRESSANTE_DISCIPLINA_ISOLADA_GRADUACAO";
        public const string PRORROGACAO_PRAZO_CONCLUSAO = "PRORROGACAO_PRAZO_CONCLUSAO";
        public const string SOLICITACAO_ALTERACAO_PLANO_ESTUDO = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO";
        public const string SOLICITACAO_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA";
        public const string SOLICITACAO_INCLUSAO_DISCIPLINA_ELETIVA = "SOLICITACAO_INCLUSAO_DISCIPLINA_ELETIVA";
        public const string SOLICITACAO_MATRICULA_INGRESSANTE_STRICTO_SENSU = "SOLICITACAO_MATRICULA_INGRESSANTE_STRICTO_SENSU";
        public const string SOLICITACAO_MATRICULA_INGRESSANTE_STRICTO_SENSU_DISCIPLINA_ISOLADA = "SOLICITACAO_MATRICULA_INGRESSANTE_STRICTO_SENSU_DISCIPLINA_ISOLADA";
        public const string SOLICITACAO_REABERTURA = "SOLICITACAO_REABERTURA";
        public const string SOLICITACAO_RENOVACAO_MATRICULA_STRICTO_SENSU = "SOLICITACAO_RENOVACAO_MATRICULA_STRICTO_SENSU";
        public const string TRANCAMENTO_MATRICULA = "TRANCAMENTO_MATRICULA";
        public const string SOLICITACAO_INTERCAMBIO = "SOLICITACAO_INTERCAMBIO";
        public const string DEPOSITO_DISSERTACAO_TESE = "DEPOSITO_DISSERTACAO_TESE";
        public const string EMISSAO_DOCUMENTO_ACADEMICO = "EMISSAO_DOCUMENTO_ACADEMICO";
        public const string EMISSAO_DIPLOMA_DIGITAL_1_VIA = "EMISSAO_DIPLOMA_DIGITAL_1_VIA";
        public const string EMISSAO_DIPLOMA_DIGITAL_2_VIA = "EMISSAO_DIPLOMA_DIGITAL_2_VIA";
        public const string EMISSAO_HISTORICO_ESCOLAR_DIGITAL = "EMISSAO_HISTORICO_ESCOLAR_DIGITAL";
        public const string ENTREGA_DOCUMENTACAO = "ENTREGA_DOCUMENTACAO";
        public const string SOLICITACAO_RENOVACAO_MATRICULA_LATO_SENSU = "SOLICITACAO_RENOVACAO_MATRICULA_LATO_SENSU";
        public const string DEPOSITO_PROJETO_QUALIFICACAO = "DEPOSITO_PROJETO_QUALIFICACAO";
        public const string ATUALIZACAO_DOCUMENTACAO_EMISSAO_DIPLOMA = "ATUALIZACAO_DOCUMENTACAO_EMISSAO_DIPLOMA";

    }
}