namespace SMC.Academico.Common.Areas.SRC.Constants
{
    public static class TOKEN_MOTIVO_SITUACAO_CANCELAMENTO
    {
        public const string EXISTENCIA_BLOQUEIO = "EXISTENCIA_BLOQUEIO";
        public const string MATRICULA_CANCELADA = "MATRICULA_CANCELADA";
        public const string MATRICULA_REALIZADA_SGP = "MATRICULA_REALIZADA_SGP";
        public const string MATRICULA_TRANCADA = "MATRICULA_TRANCADA";
        public const string REALIZACAO_MATRICULA_AUTOMATICA = "REALIZACAO_MATRICULA_AUTOMATICA";
        public const string SOLICITACAO_CANCELADA_PORTAL_ALUNO = "SOLICITACAO_CANCELADA_PORTAL_ALUNO";
        public const string SOLICITACAO_CRIADA_INDEVIDAMENTE = "SOLICITACAO_CRIADA_INDEVIDAMENTE";
        public const string ALUNO_FORMADO = "ALUNO_FORMADO";
        public const string CURSO_NAO_POSSUI_RECONHECIMENTO = "CURSO_NAO_POSSUI_RECONHECIMENTO";
        public const string ALUNO_NAO_APTO_EMISSAO_DOCUMENTO_CONCLUSAO = "ALUNO_NAO_APTO_EMISSAO_DOCUMENTO_CONCLUSAO";
        public const string ALUNO_INDEFERIU_DADOS_DOCUMENTO = "ALUNO_INDEFERIU_DADOS_DOCUMENTO";
        public const string DADOS_INCONSISTENTES = "DADOS_INCONSISTENTES";
        public const string REQUERIDO_PELO_SOLICITANTE = "REQUERIDO_PELO_SOLICITANTE";
    }
}