#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
    using SMC.Academico.Common.Areas.MAT.Enums;
    
    #line default
    #line hidden
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SRC/Views/SolicitacaoServicoFluxoBase/_SelecaoChancelaPlanoAtividade.csht" +
        "ml")]
    public partial class _Areas_SRC_Views_SolicitacaoServicoFluxoBase__SelecaoChancelaPlanoAtividade_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMC.Academico.UI.Mvc.Areas.SRC.Models.SelecaoChancelaPlanoAtividadeViewModel>
    {
        public _Areas_SRC_Views_SolicitacaoServicoFluxoBase__SelecaoChancelaPlanoAtividade_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
 using (Smc.Div().Size(SMCSize.Grid22_24).CssClass("smc-listdetailed-item").Begin())
{
    using (Smc.Div().CssClass("smc-listdetailed-conteudo").Size(SMCSize.Grid24_24).Begin())
    {
        using (Smc.Div().Size(SMCSize.Grid1_24, SMCSize.Grid24_24, SMCSize.Grid2_24, SMCSize.Grid1_24).CssClass("smc-sga-legenda-agrupamento smc-sga-legenda-agrupamento-legendas").Begin())
        {
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
       Write(Smc.LegendItem(m => m.Pertence));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                          
            if (Model.LegendaPertencePlanoEstudo.GetValueOrDefault()) {
                
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
           Write(Smc.LegendItem(m => m.SituacaoPlanoEstudo));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                           
            }
        }


        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
   Write(Smc.DisplayFor(m => m.Descricao).CssClass("smc-listdetailed-conteudo-titulo-linhaunica").Size(SMCSize.Grid18_24, SMCSize.Grid24_24, SMCSize.Grid17_24, SMCSize.Grid18_24).HideLabel());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                                                                                                                                                              
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
   Write(Smc.EditorFor(x => x.SeqItem));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                      
        var exibirNaoAlterado = ((bool)ViewBag.ChancelaFinalizada) || Model.SituacaoPlanoEstudo == MatriculaPertencePlanoEstudo.NaoAlterado;

        if (exibirNaoAlterado)
        {
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
       Write(Smc.HiddenFor(x => x.SeqSituacaoItemMatricula));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                           
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
       Write(Smc.EditorFor(x => x.SeqSituacaoItemMatricula).CssClass("smc-select-alinhamento-titulo").Size(SMCSize.Grid4_24, SMCSize.Grid24_24, SMCSize.Grid4_24, SMCSize.Grid4_24).HideLabel());

            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                                                                                                                                                               
        }

        
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
   Write(Smc.HiddenFor(x => x.Descricao));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                        
        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
   Write(Smc.HiddenFor(m => m.LegendaPertencePlanoEstudo));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\_SelecaoChancelaPlanoAtividade.cshtml"
                                                         

    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
