#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    using SMC.Academico.Common.Areas.ALN.Constants;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    using SMC.Academico.Common.Areas.MAT.Constants;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    using SMC.Academico.UI.Mvc.Areas.SRC.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    using SMC.DadosMestres.Common.Areas.PES.Enums;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    using SMC.Formularios.UI.Mvc;
    
    #line default
    #line hidden
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SRC/Views/SolicitacaoServicoFluxoBase/RegistrarEntregaDocumentos.cshtml")]
    public partial class _Areas_SRC_Views_SolicitacaoServicoFluxoBase_RegistrarEntregaDocumentos_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<RegistrarEntregaDocumentoViewModel>
    {
        public _Areas_SRC_Views_SolicitacaoServicoFluxoBase_RegistrarEntregaDocumentos_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
  
    Layout = "~/Views/Shared/_LayoutFluxo.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("MenuFluxo", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
Write(Html.Action("MenuFluxo", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 18 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
Write(Smc.SGFTemplate().Secao().Token(MatriculaTokens.PAGINA_INSTRUCOES_REGISTRO_DOCUMENTO));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 20 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
 if (Model.DocumentosPendentes)
{
    using (Smc.Div().Size(SMCSize.Grid24_24).CssClass("smc-sga-mensagem smc-sga-mensagem-alerta").Begin())
    {
        using (Smc.Div().CssClass(" smc-sga-ico-mensagem").Begin())
        {
        }


            
            #line default
            #line hidden
WriteLiteral("        <p>");

            
            #line 28 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
      Write(Smc.GetUIResource("Texto_Documentos_Obrigatorios_Pendentes"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 29 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    }
}
else
{
    using (Smc.Div().Size(SMCSize.Grid24_24).CssClass("smc-sga-mensagem smc-sga-mensagem-informativa").Begin())
    {
        using (Smc.Div().CssClass("smc-sga-ico-mensagem").Begin())
        {
        }

            
            #line default
            #line hidden
WriteLiteral("        <p> ");

            
            #line 38 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
       Write(Smc.GetUIResource("Texto_Documentos_Obrigatorios_Enviados"));

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 39 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
    }
}

            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
  
    var buttonSet = Smc.ButtonSet().Size(SMCSize.Grid24_24);

    var backUrl = Url.Action("EntrarEtapa", new { @seqSolicitacaoServico = new SMCEncryptedLong(Model.SeqSolicitacaoServico), @SeqConfiguracaoEtapa = new SMCEncryptedLong(Model.SeqConfiguracaoEtapa) });

    if (Model.ExibirSegundaVia == true)
    {
        buttonSet.AddButton(Smc.Button("VisualizarContrato", "TermoAdesao", new { seqSolicitacaoMatricula = new SMCEncryptedLong(Model.SeqSolicitacaoServico) })
                              .Attribute("target", "_blank")
                              .Type(SMCButtonType.Link)
                              .CssClass("smc-btn-documento-icotext"));
    }

    buttonSet.AddButton(Smc.Button(SMCMvcConsts.MODAL_BEHAVIOR_OPEN)
                       .Action("RegistrarDocumentos", "RegistroDocumentosItemRoute", new
                       {
                           @seqSolicitacaoServico = Model.SeqSolicitacaoServico,
                           @backUrl = backUrl,
                           @area = string.Empty,
                           @seqPessoaAtuacao = Model.SeqPessoaAtuacao
                       })
                        .Ajax(isPost: false)
                        .CssClass("smc-sga-btn-inline")
                        .SecurityToken(UC_MAT_003_09_01.SELECIONAR_TURMAS)
                        .Attribute(SMCMvcConsts.MODAL_ID, "modalRegistrarDocumentos")
                        .Attribute(SMCMvcConsts.MODAL_TITLE, Smc.GetUIResource("Modal_Title_Registrar_Documentos"))
                        .Text(Smc.GetUIResource("Label_Registrar_Documentos"))
                        .Tooltip(Smc.GetUIResource("Label_Registrar_Documentos")));

    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
Write(buttonSet);

            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
              ;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 73 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
  
    var grupoDocumentos = Model.Documentos.GroupBy(g => g.DescricaoEtapa);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 78 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
Write(Smc.Legend("legenda", SMCOrientation.Horizontal).CssClass("smc-sga-legenda").Items<SMC.Academico.Common.Areas.SRC.Enums.SituacaoEntregaDocumentoLista>());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 80 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
   foreach (var etapa in grupoDocumentos)
    {

        
            
            #line default
            #line hidden
            
            #line 83 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
         using (Smc.Div("divDescricaoEtapa").Begin())
        {

            
            #line default
            #line hidden
WriteLiteral("            <br />\r\n");

WriteLiteral("            <legend");

WriteLiteral(" class=\"fieldset>legend\"");

WriteLiteral(" style=\"color: #0083a2;\"");

WriteLiteral(">");

            
            #line 86 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                                                               Write(etapa.Key);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n");

            
            #line 87 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
        }
            
            #line default
            #line hidden
            
            #line 87 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
         
        if (Model.DocumentosObrigatorios.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).ToList() != null &&
            Model.DocumentosObrigatorios.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).Any())
        {
            
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
             using (Smc.Fieldset("obrigatorios").Begin())
            {
                
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
           Write(Html.Partial(Smc.GetExternalView(SMC.Academico.UI.Mvc.AcademicoExternalViews._REGISTRAR_REGISTRAR_DOC_ITEM), Model.DocumentosObrigatorios.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).ToList()));

            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                                                                                                                                                                                                                                                      
            }
            
            #line default
            #line hidden
            
            #line 94 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
             
        }

        
            
            #line default
            #line hidden
            
            #line 97 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
         if (Model.GruposDocumentosObrigatorios.SelectMany(sm => sm.Value).Where(w => w.DescricaoEtapa == etapa.Key).ToList() != null && Model.GruposDocumentosObrigatorios.SelectMany(sm => sm.Value).Where(w => w.DescricaoEtapa == etapa.Key).Any())
        {
            using (Smc.Fieldset("grupoObrigatorios").Begin())
            {
                foreach (var grupo in Model.GruposDocumentosObrigatorios.Where(w => w.Value.All(a => a.DescricaoEtapa == etapa.Key)).ToList())
                {
                    TempData["__GrupoDocumentoObrigatorio"] = grupo.Key;
                    using (Smc.Fieldset("grupoObrigatorios_" + grupo.Key.Seq).LegendText(grupo.Key.Descricao).CssClass("smc-sga-fieldset-secundario").Begin())
                    {
                        
            
            #line default
            #line hidden
            
            #line 106 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                   Write(Html.Partial(Smc.GetExternalView(SMC.Academico.UI.Mvc.AcademicoExternalViews._REGISTRAR_REGISTRAR_DOC_ITEM), grupo.Value.Where(w => w.DescricaoEtapa == etapa.Key).ToList()));

            
            #line default
            #line hidden
            
            #line 106 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                                                                                                                                                                                                     
                    }
                }
            }
        }
            
            #line default
            #line hidden
            
            #line 110 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
         

        if (Model.DocumentosOpcionais.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).ToList() != null &&
            Model.DocumentosOpcionais.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).Any())
        {
            
            
            #line default
            #line hidden
            
            #line 115 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
             using (Smc.Fieldset("opcionais").Begin())
            {
                
            
            #line default
            #line hidden
            
            #line 117 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
           Write(Html.Partial(Smc.GetExternalView(SMC.Academico.UI.Mvc.AcademicoExternalViews._REGISTRAR_REGISTRAR_DOC_ITEM), Model.DocumentosOpcionais.OfType<SolicitacaoDocumentoViewModel>().Where(w => w.DescricaoEtapa == etapa.Key).ToList()));

            
            #line default
            #line hidden
            
            #line 117 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                                                                                                                                                                                                                                                   
            }
            
            #line default
            #line hidden
            
            #line 118 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
             
        }
    }

    
            
            #line default
            #line hidden
            
            #line 122 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
      
        var buttonSet2 = Smc.ButtonSet().Size(SMCSize.Grid24_24).CssClass("smc-sga-margin-top-20");

        
            
            #line default
            #line hidden
            
            #line 125 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
   Write(buttonSet2);

            
            #line default
            #line hidden
            
            #line 125 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                   ;
    
            
            #line default
            #line hidden
            
            #line 126 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
     

    
            
            #line default
            #line hidden
            
            #line 128 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
     using (Smc.Form("frmPagina").Ajax("#divSelecaoAtividadeAluno").Begin())
    {
        
            
            #line default
            #line hidden
            
            #line 130 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
   Write(Html.Partial("_BotoesNavegacao", Model));

            
            #line default
            #line hidden
            
            #line 130 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                                                
    }
            
            #line default
            #line hidden
            
            #line 131 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
     

    
            
            #line default
            #line hidden
            
            #line 133 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
     using (Smc.ModalWindow("modalRegistrarDocumentos")
        .Form("frmRegistrar", "SalvarRegistroDocumentos", "RegistroDocumentosItemRoute", new { area = string.Empty }, closeOnSubmit: true, config: x => x.Ajax())
        .Size(SMCModalWindowSize.Largest)
        .Button(SMCButtonBehavior.Salvar, "SalvarRegistroDocumentos", "RegistroDocumentosItemRoute", new { area = string.Empty }, config: bnt => bnt.DisplayMode(SMCButtonDisplayMode.TextAndIcon).Highlight())
        .Button(SMCButtonBehavior.Fechar, config: bnt => bnt.DisplayMode(SMCButtonDisplayMode.TextAndIcon))
        .Begin()) { }
            
            #line default
            #line hidden
            
            #line 138 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\RegistrarEntregaDocumentos.cshtml"
                     
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
