#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
    using SMC.Academico.Common.Areas.CNC.Constants;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
    using SMC.Academico.Common.Areas.SRC.Constants;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
    using SMC.Formularios.UI.Mvc;
    
    #line default
    #line hidden
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SRC/Views/SolicitacaoServicoFluxoBase/SolicitacaoDispensaItensCursados.cs" +
        "html")]
    public partial class _Areas_SRC_Views_SolicitacaoServicoFluxoBase_SolicitacaoDispensaItensCursados_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMC.Academico.UI.Mvc.Areas.SRC.Models.SolicitacaoDispensaItensCursadosViewModel>
    {
        public _Areas_SRC_Views_SolicitacaoServicoFluxoBase_SolicitacaoDispensaItensCursados_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
  
    Layout = "~/Views/Shared/_LayoutFluxo.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("MenuFluxo", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
Write(Html.Action("MenuFluxo", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 15 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
Write(Smc.SGFTemplate().Secao().Token(TOKEN_SOLICITACAO_SERVICO.SECAO_TEXTO_DISPENSA_ITENS_CURSADOS));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 17 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
 using (Smc.Form("frmPagina").Ajax("#divSolicitacaoDispensaItensCursados").Begin())
{

    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
Write(Smc.EditorFor(m => m.backUrl));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                  
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
Write(Smc.HiddenFor(m => m.DispensaTotalCargaHorariaHoras));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                         

    if (Model.ExibirIntegralizacao == true)
    {
        var buttonSet = Smc.ButtonSet().Size(SMCSize.Grid24_24);

        // INTEGRALIZAÇÃO CURRICULAR
        SMCButtonFluentConfiguration buttonIntegralizacao = Smc.Button(SMCMvcConsts.MODAL_BEHAVIOR_OPEN)
                .Action("ConsultaIntegralizacaoCurricular", "IntegralizacaoCurricularRoute", new { @seqPessoaAtuacao = Model.SeqPessoaAtuacao, Area = "" })
                .Ajax(isPost: false)
                .Attribute(SMCMvcConsts.MODAL_ID, "modalIntegralizacaoCurricular")
                .Attribute(SMCMvcConsts.MODAL_TITLE, Smc.GetUIResource("Modal_Title_Integralizacao_Curricular"))
                .Text(Smc.GetUIResource("Botao_Integralizacao_Curricular"))
                .SecurityToken(UC_CNC_001_02_01.EXIBIR_INTEGRALIZACAO_CURRICULAR)
                .Tooltip(Smc.GetUIResource("Botao_Integralizacao_Curricular_Tooltip"));

        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
   Write(buttonSet.AddButton(buttonIntegralizacao));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                  ;
    }

    using (Smc.Div("divItensCursadosOutrasInstituicoes").Size(SMCSize.Grid24_24).Begin())
    {
        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
   Write(Smc.EditorFor(m => m.ItensCursadosOutrasInstituicoes));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                              
    }

    using (Smc.Div("divItensCursadosNestaInstituicao").Size(SMCSize.Grid24_24).Begin())
    {
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
   Write(Smc.EditorFor(m => m.ItensCursadosNestaInstituicao));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                            
    }

    using (Smc.Fieldset("TotalItensCursados").Size(SMCSize.Grid11_24, SMCSize.Grid24_24, SMCSize.Grid11_24, SMCSize.Grid11_24).Begin())
    {

        using (Smc.Div("TotaisCargaHoraria").CssClass("smc-sga-totalizador").Size(SMCSize.Grid11_24, SMCSize.Grid24_24, SMCSize.Grid11_24, SMCSize.Grid11_24).Begin())
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteAttribute("class", Tuple.Create(" class=\"", 2288), Tuple.Create("\"", 2428)
            
            #line 55 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
, Tuple.Create(Tuple.Create("", 2296), Tuple.Create<System.Object, System.Int32>(SMCSizeHelper.GetSizeClasses(SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24)
            
            #line default
            #line hidden
, 2296), false)
, Tuple.Create(Tuple.Create(" ", 2401), Tuple.Create("smc-sga-totalizador-titulo", 2402), true)
);

WriteLiteral(">");

            
            #line 55 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                          Write(Smc.GetUIResource("Titulo_Label_TotalCargaHoraria"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 56 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
       Write(Smc.DisplayFor(m => m.CursadosTotalCargaHorariaHoras).Attribute("id", "CursadosTotalCargaHorariaHoras").CssClass("smc-sga-totalizador-valor").HideLabel().Size(SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                                                                                                                       
            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
       Write(Smc.DisplayFor(m => m.CursadosTotalCargaHorariaHorasAula).Attribute("id", "CursadosTotalCargaHorariaHorasAula").CssClass("smc-sga-totalizador-valor").HideLabel().Size(SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                                                                                                                               

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteAttribute("class", Tuple.Create(" class=\"", 3014), Tuple.Create("\"", 3161)
            
            #line 58 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
, Tuple.Create(Tuple.Create("", 3022), Tuple.Create<System.Object, System.Int32>(SMCSizeHelper.GetSizeClasses(SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24)
            
            #line default
            #line hidden
, 3022), false)
, Tuple.Create(Tuple.Create(" ", 3127), Tuple.Create("smc-sga-totalizador-texto-detalhe", 3128), true)
);

WriteLiteral(">");

            
            #line 58 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                                 Write(Smc.GetUIResource("Detalhe_Label_TotalCargaHorariaHoras"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("            <span");

WriteAttribute("class", Tuple.Create(" class=\"", 3247), Tuple.Create("\"", 3394)
            
            #line 59 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
, Tuple.Create(Tuple.Create("", 3255), Tuple.Create<System.Object, System.Int32>(SMCSizeHelper.GetSizeClasses(SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24, SMCSize.Grid12_24)
            
            #line default
            #line hidden
, 3255), false)
, Tuple.Create(Tuple.Create(" ", 3360), Tuple.Create("smc-sga-totalizador-texto-detalhe", 3361), true)
);

WriteLiteral(">");

            
            #line 59 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                                 Write(Smc.GetUIResource("Detalhe_Label_TotalCargaHorariaHorasAula"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 60 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
        }

        using (Smc.Div("TotaisCreditos").CssClass("smc-sga-totalizador col-md-offset-2 col-sm-offset-2 col-lg-offset-2").Size(SMCSize.Grid11_24, SMCSize.Grid24_24, SMCSize.Grid11_24, SMCSize.Grid11_24).Begin())
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteAttribute("class", Tuple.Create(" class=\"", 3720), Tuple.Create("\"", 3860)
            
            #line 64 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
, Tuple.Create(Tuple.Create("", 3728), Tuple.Create<System.Object, System.Int32>(SMCSizeHelper.GetSizeClasses(SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24)
            
            #line default
            #line hidden
, 3728), false)
, Tuple.Create(Tuple.Create(" ", 3833), Tuple.Create("smc-sga-totalizador-titulo", 3834), true)
);

WriteLiteral(">");

            
            #line 64 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                          Write(Smc.GetUIResource("Titulo_Label_TotalCreditos"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 65 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
       Write(Smc.DisplayFor(m => m.CursadosTotalCreditos).Attribute("id", "CursadosTotalCreditos").CssClass("smc-sga-totalizador-valor").HideLabel().Size(SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24, SMCSize.Grid24_24));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                                                                                                                                                                                                                     
        }
    }
    
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
Write(Html.Partial("_BotoesNavegacao", Model));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
                                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 71 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
 using (Smc.ModalWindow("modalIntegralizacaoCurricular")
           .Size(SMCModalWindowSize.Largest)
           .Button(SMCButtonBehavior.Fechar, config: bnt => bnt.DisplayMode(SMCButtonDisplayMode.TextAndIcon))
           .Begin()) { }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4499), Tuple.Create("\"", 4598)
            
            #line 78 "..\..\Areas\SRC\Views\SolicitacaoServicoFluxoBase\SolicitacaoDispensaItensCursados.cshtml"
, Tuple.Create(Tuple.Create("", 4505), Tuple.Create<System.Object, System.Int32>(Url.SMCBuscarRecursoGlobalAplicacao("Scripts/Areas/SRC/SolicitacaoDispensaItensCursados.js")
            
            #line default
            #line hidden
, 4505), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
