//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.SRC.Views.Processo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.SRC.Views.Processo.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento SAT.
        /// </summary>
        public static string AGENDAMENTOSAT_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("AGENDAMENTOSAT_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessar etapa.
        /// </summary>
        public static string Botao_AcessarEtapa {
            get {
                return ResourceManager.GetString("Botao_AcessarEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessar etapa.
        /// </summary>
        public static string Botao_AcessarEtapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_AcessarEtapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colocar etapa em manutenção.
        /// </summary>
        public static string botao_colocar_manutencao {
            get {
                return ResourceManager.GetString("botao_colocar_manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colocar etapa em manutenção.
        /// </summary>
        public static string botao_colocar_manutencao_tooltip {
            get {
                return ResourceManager.GetString("botao_colocar_manutencao_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Etapas.
        /// </summary>
        public static string Botao_ConfiguracaoEtapa {
            get {
                return ResourceManager.GetString("Botao_ConfiguracaoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Etapas.
        /// </summary>
        public static string Botao_ConfiguracaoEtapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ConfiguracaoEtapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Processo.
        /// </summary>
        public static string Botao_ConfiguracaoProcesso {
            get {
                return ResourceManager.GetString("Botao_ConfiguracaoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Processo.
        /// </summary>
        public static string Botao_ConfiguracaoProcesso_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ConfiguracaoProcesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Etapa.
        /// </summary>
        public static string Botao_ConfigurarEtapa {
            get {
                return ResourceManager.GetString("Botao_ConfigurarEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Processo.
        /// </summary>
        public static string Botao_CopiarProcesso {
            get {
                return ResourceManager.GetString("Botao_CopiarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Processo.
        /// </summary>
        public static string Botao_CopiarProcesso_Tooltip {
            get {
                return ResourceManager.GetString("Botao_CopiarProcesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Botao_EditarProcesso {
            get {
                return ResourceManager.GetString("Botao_EditarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar etapa.
        /// </summary>
        public static string Botao_EncerrarEtapa {
            get {
                return ResourceManager.GetString("Botao_EncerrarEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar processo.
        /// </summary>
        public static string Botao_EncerrarProcesso {
            get {
                return ResourceManager.GetString("Botao_EncerrarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar processo.
        /// </summary>
        public static string Botao_EncerrarProcesso_Tooltip {
            get {
                return ResourceManager.GetString("Botao_EncerrarProcesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Escalonamento das Etapas.
        /// </summary>
        public static string Botao_EscalonamentoEtapa {
            get {
                return ResourceManager.GetString("Botao_EscalonamentoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Escalonamento das Etapas.
        /// </summary>
        public static string Botao_EscalonamentoEtapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_EscalonamentoEtapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir etapa.
        /// </summary>
        public static string Botao_ExcluirEtapa {
            get {
                return ResourceManager.GetString("Botao_ExcluirEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Botao_ExcluirProcesso {
            get {
                return ResourceManager.GetString("Botao_ExcluirProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Grupo de Escalonamento.
        /// </summary>
        public static string Botao_GruposEscalonamento {
            get {
                return ResourceManager.GetString("Botao_GruposEscalonamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Grupo de Escalonamento.
        /// </summary>
        public static string Botao_GruposEscalonamento_Tooltip {
            get {
                return ResourceManager.GetString("Botao_GruposEscalonamento_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberar etapa.
        /// </summary>
        public static string botao_liberar_etapa {
            get {
                return ResourceManager.GetString("botao_liberar_etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberar etapa.
        /// </summary>
        public static string botao_liberar_etapa_tooltip {
            get {
                return ResourceManager.GetString("botao_liberar_etapa_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo processo.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo processo.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Relatório de Posição Consolidada.
        /// </summary>
        public static string Botao_PosicaoConsolidada {
            get {
                return ResourceManager.GetString("Botao_PosicaoConsolidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Relatório de Posição Consolidada.
        /// </summary>
        public static string Botao_PosicaoConsolidada_Tooltip {
            get {
                return ResourceManager.GetString("Botao_PosicaoConsolidada_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparar renovação matrícula.
        /// </summary>
        public static string Botao_PreparacaoRematricula {
            get {
                return ResourceManager.GetString("Botao_PreparacaoRematricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparar renovação matrícula.
        /// </summary>
        public static string Botao_PreparacaoRematricula_Tooltip {
            get {
                return ResourceManager.GetString("Botao_PreparacaoRematricula_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar etapa .
        /// </summary>
        public static string Botao_ProcessoEtapa {
            get {
                return ResourceManager.GetString("Botao_ProcessoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar etapa do processo.
        /// </summary>
        public static string Botao_ProcessoEtapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ProcessoEtapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Notificação das Etapas.
        /// </summary>
        public static string Botao_ProcessoEtapaConfiguracaoNotificacao {
            get {
                return ResourceManager.GetString("Botao_ProcessoEtapaConfiguracaoNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Notificação das Etapas.
        /// </summary>
        public static string Botao_ProcessoEtapaConfiguracaoNotificacao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ProcessoEtapaConfiguracaoNotificacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabrir Processo.
        /// </summary>
        public static string Botao_ReabrirProcesso {
            get {
                return ResourceManager.GetString("Botao_ReabrirProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabrir Processo.
        /// </summary>
        public static string Botao_ReabrirProcesso_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ReabrirProcesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitações do processo.
        /// </summary>
        public static string Botao_Solicitacoes {
            get {
                return ResourceManager.GetString("Botao_Solicitacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitações do processo.
        /// </summary>
        public static string Botao_Solicitacoes_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Solicitacoes_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção indisponível. A etapa está encerrada..
        /// </summary>
        public static string boto_manutencao_situacao_encerrada_instructions {
            get {
                return ResourceManager.GetString("boto_manutencao_situacao_encerrada_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Processo.
        /// </summary>
        public static string CopiarProcesso_Title {
            get {
                return ResourceManager.GetString("CopiarProcesso_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar.
        /// </summary>
        public static string DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string Destino_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("Destino_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Processo.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas Origem x Destino.
        /// </summary>
        public static string EtapasCopiar_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EtapasCopiar_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da etapa &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Etapa_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Etapa_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Etapa.
        /// </summary>
        public static string Exclusao_Etapa_Title {
            get {
                return ResourceManager.GetString("Exclusao_Etapa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas previstas no Template do Serviço.
        /// </summary>
        public static string Fieldset_EtapasSGF {
            get {
                return ResourceManager.GetString("Fieldset_EtapasSGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas do processo.
        /// </summary>
        public static string gridEtapas_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridEtapas_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas do processo.
        /// </summary>
        public static string gridPadrao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridPadrao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de escalonamento Origem x Destino.
        /// </summary>
        public static string GruposEscalonamentoCopiar_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("GruposEscalonamentoCopiar_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Processo.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central de Processos.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar etapa?.
        /// </summary>
        public static string Label_Associar {
            get {
                return ResourceManager.GetString("Label_Associar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Label_Descricao {
            get {
                return ResourceManager.GetString("Label_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa obrigatória?.
        /// </summary>
        public static string Label_Obrigatorio {
            get {
                return ResourceManager.GetString("Label_Obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do processo &quot;{0}&quot;?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão do Processo.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma colocar a etapa &quot;{0}&quot; em manutenção?.
        /// </summary>
        public static string mensagem_etapa_em_manutencao {
            get {
                return ResourceManager.GetString("mensagem_etapa_em_manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a liberação da etapa &quot;{0}&quot;?.
        /// </summary>
        public static string mensagem_liberar_etapa {
            get {
                return ResourceManager.GetString("mensagem_liberar_etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a liberação da etapa &quot;{0}&quot;?.
        /// </summary>
        public static string mensagem_liberar_etapa1 {
            get {
                return ResourceManager.GetString("mensagem_liberar_etapa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção indisponível. Para o cadastro de grupos de escalonamento é necessário que os escalonamentos por etapa sejam previamente cadastrados..
        /// </summary>
        public static string MSG_BtnGrupoEscalonamentoDesabilitado {
            get {
                return ResourceManager.GetString("MSG_BtnGrupoEscalonamentoDesabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Após o encerramento do processo nenhuma alteração poderá ser realizada. Confirma o encerramento?.
        /// </summary>
        public static string MSG_Confirmacao_EncerrarProcesso {
            get {
                return ResourceManager.GetString("MSG_Confirmacao_EncerrarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao reabrir, a data de encerramento será excluída e o processo ficará ativo. Confirma a reabertura?.
        /// </summary>
        public static string MSG_Confirmacao_ReabrirProcesso {
            get {
                return ResourceManager.GetString("MSG_Confirmacao_ReabrirProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Após concluir a cópia do processo:
        ///{0}
        ///- Confira as parametrizações do processo x etapas e se necessário altere os parâmetros,
        ///{0}
        ///- E para concluir a disponibilização do processo, execute o comando Liberar Etapa para todas as etapas do processo..
        /// </summary>
        public static string MSG_CopiarProcesso {
            get {
                return ResourceManager.GetString("MSG_CopiarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Após concluir a cópia do processo:
        ///{0}
        ///- Atualize o período de vigência dos escalonamentos por etapa,
        ///{0}
        ///- Atualize a data de vencimento das configurações de parcela se houver,
        ///{0}
        ///- Confira as parametrizações do processo x etapas e se necessário altere os parâmetros,
        ///{0}
        ///- E para concluir a disponibilização do processo, execute o comando Liberar Etapa para todas as etapas do processo..
        /// </summary>
        public static string MSG_CopiarProcessoPrazoEscalonamento {
            get {
                return ResourceManager.GetString("MSG_CopiarProcessoPrazoEscalonamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção indisponível. O processo está encerrado..
        /// </summary>
        public static string MSG_ProcessoEncerrado {
            get {
                return ResourceManager.GetString("MSG_ProcessoEncerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. O período do processo não se encontra vigente..
        /// </summary>
        public static string MSG_ProcessoVigente {
            get {
                return ResourceManager.GetString("MSG_ProcessoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        public static string Origem_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("Origem_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção!.
        /// </summary>
        public static string TITLE_Confirmacao_EncerrarProcesso {
            get {
                return ResourceManager.GetString("TITLE_Confirmacao_EncerrarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabrir Processo.
        /// </summary>
        public static string TITLE_Confirmacao_ReabrirProcesso {
            get {
                return ResourceManager.GetString("TITLE_Confirmacao_ReabrirProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa em Manutenção.
        /// </summary>
        public static string title_modal_etapa_em_manutencao {
            get {
                return ResourceManager.GetString("title_modal_etapa_em_manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberação de Etapa.
        /// </summary>
        public static string title_modal_liberar_etapa {
            get {
                return ResourceManager.GetString("title_modal_liberar_etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar etapa.
        /// </summary>
        public static string Titulo_Encerrar_Etapa {
            get {
                return ResourceManager.GetString("Titulo_Encerrar_Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Etapa do Processo.
        /// </summary>
        public static string Titulo_ProcessoEtapa {
            get {
                return ResourceManager.GetString("Titulo_ProcessoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades associadas.
        /// </summary>
        public static string UnidadesResponsaveis_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("UnidadesResponsaveis_Detalhe_Titulo", resourceCulture);
            }
        }
    }
}
