//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CUR.Views.InstituicaoNivelTipoComponenteCurricular.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CUR.Views.InstituicaoNivelTipoComponenteCurricular.A" +
                            "pp_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Divisão e Entidade.
        /// </summary>
        public static string Aba_Title_0 {
            get {
                return ResourceManager.GetString("Aba_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string Aba_Title_1 {
            get {
                return ResourceManager.GetString("Aba_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar tipo de componente curricular.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar tipo de componente curricular.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga horária e créditos.
        /// </summary>
        public static string CARGA_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("CARGA_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Associação de  Tipo de Componente Curricular.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ementa.
        /// </summary>
        public static string EMENTA_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("EMENTA_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade responsável.
        /// </summary>
        public static string ENTIDADE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ENTIDADE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Componente Curricular Associados.
        /// </summary>
        public static string gridPadrao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridPadrao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar  Tipo de Componente Curricular.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de  Tipo de Componente Curricular  x Instituição e Nível de Ensino.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de componente curricular.
        /// </summary>
        public static string Label_TipoComponenteCurricular {
            get {
                return ResourceManager.GetString("Label_TipoComponenteCurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de divisão de componente curricular.
        /// </summary>
        public static string Label_TipoDivisaoComponente {
            get {
                return ResourceManager.GetString("Label_TipoDivisaoComponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da associação do  tipo de componente curricular &quot;{0}&quot; com o nível de ensino &quot;{1}&quot;?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Associação de  Tipo de Componente Curricular.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string PARAMETRO_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("PARAMETRO_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de divisão de componente curricular.
        /// </summary>
        public static string TiposDivisaoComponente_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("TiposDivisaoComponente_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Componente.
        /// </summary>
        public static string Wizard_Title_0 {
            get {
                return ResourceManager.GetString("Wizard_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Divisão e Entidade.
        /// </summary>
        public static string Wizard_Title_1 {
            get {
                return ResourceManager.GetString("Wizard_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string Wizard_Title_2 {
            get {
                return ResourceManager.GetString("Wizard_Title_2", resourceCulture);
            }
        }
    }
}
