//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CAM.Views.CicloLetivoTipoEvento.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CAM.Views.CicloLetivoTipoEvento.App_LocalResources.U" +
                            "IResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alterada com sucesso..
        /// </summary>
        public static string Alterar_Sucesso {
            get {
                return ResourceManager.GetString("Alterar_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova parametrização de tipo de evento letivo.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova parametrização de tipo de evento letivo.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Parametrização de Tipo de Evento Letivo.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} excluída com sucesso..
        /// </summary>
        public static string Excluir_Sucesso {
            get {
                return ResourceManager.GetString("Excluir_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string fieldset_parametros {
            get {
                return ResourceManager.GetString("fieldset_parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evento.
        /// </summary>
        public static string fieldset_tipo_evento {
            get {
                return ResourceManager.GetString("fieldset_tipo_evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrizações.
        /// </summary>
        public static string gridPadrao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridPadrao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} incluída com sucesso..
        /// </summary>
        public static string Incluir_Sucesso {
            get {
                return ResourceManager.GetString("Incluir_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Parametrização de Tipo de Evento Letivo.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Parametrização de Tipo de Evento Letivo.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da parametrização de tipo de evento letivo?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Parametrização de Tipo de Evento Letivo.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de evento selecionado abrange todos os níveis de ensino..
        /// </summary>
        public static string MSG_GeralComParametro {
            get {
                return ResourceManager.GetString("MSG_GeralComParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de evento selecionado abrange todos os níveis de ensino e não exige nenhum parâmetro..
        /// </summary>
        public static string MSG_GeralSemParametro {
            get {
                return ResourceManager.GetString("MSG_GeralSemParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de evento selecionado não exige nenhum parâmetro adicional, além do nível de ensino, que deverá ser informado no cadastro do evento..
        /// </summary>
        public static string MSG_PorNivelEnsinoSemParametro {
            get {
                return ResourceManager.GetString("MSG_PorNivelEnsinoSemParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveis de ensino.
        /// </summary>
        public static string NiveisEnsino_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("NiveisEnsino_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string Parametros_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Parametros_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evento.
        /// </summary>
        public static string Wizard_Title_0 {
            get {
                return ResourceManager.GetString("Wizard_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string Wizard_Title_1 {
            get {
                return ResourceManager.GetString("Wizard_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Wizard_Title_2 {
            get {
                return ResourceManager.GetString("Wizard_Title_2", resourceCulture);
            }
        }
    }
}
