//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.ALN.Views.TermoIntercambio.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.ALN.Views.TermoIntercambio.App_LocalResources.Metada" +
                            "taResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        internal static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório preencher cpf ou passaporte.
        /// </summary>
        internal static string Cpf_FillInstructions {
            get {
                return ResourceManager.GetString("Cpf_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF ou Passaporte.
        /// </summary>
        internal static string CPFouPassaporte {
            get {
                return ResourceManager.GetString("CPFouPassaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        internal static string DataFim {
            get {
                return ResourceManager.GetString("DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        internal static string DataInicio {
            get {
                return ResourceManager.GetString("DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de ensino externa.
        /// </summary>
        internal static string InstituicaoEnsinoExterna {
            get {
                return ResourceManager.GetString("InstituicaoEnsinoExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituições de ensino parceiras.
        /// </summary>
        internal static string InstituicoesExternas {
            get {
                return ResourceManager.GetString("InstituicoesExternas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da alteração.
        /// </summary>
        internal static string Justificativa {
            get {
                return ResourceManager.GetString("Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        internal static string ParceriaIntercambioVigenciaViewModel_DataFim {
            get {
                return ResourceManager.GetString("ParceriaIntercambioVigenciaViewModel_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        internal static string ParceriaIntercambioVigenciaViewModel_DataInicio {
            get {
                return ResourceManager.GetString("ParceriaIntercambioVigenciaViewModel_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pessoas {
            get {
                return ResourceManager.GetString("Pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas que utilizarão o termo.
        /// </summary>
        internal static string Pessoas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Pessoas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório preencher cpf ou passaporte.
        /// </summary>
        internal static string Pessoas_FillInstructions {
            get {
                return ResourceManager.GetString("Pessoas_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui anexo?.
        /// </summary>
        internal static string PossuiAnexo {
            get {
                return ResourceManager.GetString("PossuiAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa?.
        /// </summary>
        internal static string ProcessoNegociacao {
            get {
                return ResourceManager.GetString("ProcessoNegociacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de ensino externa.
        /// </summary>
        internal static string SeqParceriaIntercambioInstituicaoExterna {
            get {
                return ResourceManager.GetString("SeqParceriaIntercambioInstituicaoExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de termo .
        /// </summary>
        internal static string SeqParceriaIntercambioTipoTermo {
            get {
                return ResourceManager.GetString("SeqParceriaIntercambioTipoTermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de termo.
        /// </summary>
        internal static string SeqTipoTermoIntercambio {
            get {
                return ResourceManager.GetString("SeqTipoTermoIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa?.
        /// </summary>
        internal static string TermoIntercambioCabecalhoViewModel_Ativo {
            get {
                return ResourceManager.GetString("TermoIntercambioCabecalhoViewModel_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em processo de renovação.
        /// </summary>
        internal static string TermoIntercambioCabecalhoViewModel_ProcessoNegociacao {
            get {
                return ResourceManager.GetString("TermoIntercambioCabecalhoViewModel_ProcessoNegociacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termo de intercâmbio.
        /// </summary>
        internal static string TermoIntercambioDynamicModel {
            get {
                return ResourceManager.GetString("TermoIntercambioDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas que utilizarão o termo.
        /// </summary>
        internal static string TermoIntercambioTipoMobilidadeViewModel_Pessoas {
            get {
                return ResourceManager.GetString("TermoIntercambioTipoMobilidadeViewModel_Pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de mobilidade.
        /// </summary>
        internal static string TipoMobilidade {
            get {
                return ResourceManager.GetString("TipoMobilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de parceria.
        /// </summary>
        internal static string TipoParceriaIntercambio {
            get {
                return ResourceManager.GetString("TipoParceriaIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de termo.
        /// </summary>
        internal static string TiposTermo {
            get {
                return ResourceManager.GetString("TiposTermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de termo.
        /// </summary>
        internal static string TipoTermoIntercambio {
            get {
                return ResourceManager.GetString("TipoTermoIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total benefícios.
        /// </summary>
        internal static string TotalBeneficios {
            get {
                return ResourceManager.GetString("TotalBeneficios", resourceCulture);
            }
        }
    }
}
