namespace SMC.Academico.Common.Areas.Shared.Constants
{
    public static class TOKENS_ETAPA_SGF
    {
		public const string SOLICITACAO_MATRICULA = "SOLICITACAO_MATRICULA";
		public const string CHANCELA_PLANO_ESTUDO = "CHANCELA_PLANO_ESTUDO";
		public const string CHANCELA_RENOVACAO_MATRICULA = "CHANCELA_RENOVACAO_MATRICULA";

		public const string ASSINATURA_REGISTRO_DIPLOMA = "ASSINATURA_REGISTRO_DIPLOMA";
		public const string ASSINATURA_REGISTRO_DOCUMENTO = "ASSINATURA_REGISTRO_DOCUMENTO";
		public const string CADASTRO_DOCUMENTO_CONCLUSAO = "CADASTRO_DOCUMENTO_CONCLUSAO";
		public const string IMPRESSAO_DOCUMENTO_CONCLUSAO = "IMPRESSAO_DOCUMENTO_CONCLUSAO";
		public const string IMPRESSAO_DOCUMENTO = "IMPRESSAO_DOCUMENTO";
		public const string EMISSAO_DOCUMENTO = "EMISSAO_DOCUMENTO";

	}
}