//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.ORG.Views.AtoNormativo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.ORG.Views.AtoNormativo.App_LocalResources.UIResource" +
                            "", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Gerais.
        /// </summary>
        internal static string Aba_Title_0 {
            get {
                return ResourceManager.GetString("Aba_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de publicação.
        /// </summary>
        internal static string Aba_Title_1 {
            get {
                return ResourceManager.GetString("Aba_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string Aba_Title_2 {
            get {
                return ResourceManager.GetString("Aba_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar entidades.
        /// </summary>
        internal static string Botao_AssociacaoEntidades {
            get {
                return ResourceManager.GetString("Botao_AssociacaoEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar entidades.
        /// </summary>
        internal static string Botao_AssociacaoEntidades_Tooltip {
            get {
                return ResourceManager.GetString("Botao_AssociacaoEntidades_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço eletrônico.
        /// </summary>
        internal static string Botao_Endereco_Eletronico {
            get {
                return ResourceManager.GetString("Botao_Endereco_Eletronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço eletrônico.
        /// </summary>
        internal static string Botao_Endereco_Eletronico_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Endereco_Eletronico_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo ato normativo.
        /// </summary>
        internal static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo ato normativo.
        /// </summary>
        internal static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados gerais.
        /// </summary>
        internal static string DADOSGERAIS_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DADOSGERAIS_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de publicação.
        /// </summary>
        internal static string DADOSPUBLICACAO_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DADOSPUBLICACAO_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Ato Normativo.
        /// </summary>
        internal static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade associada.
        /// </summary>
        internal static string ENTIDADEASSOCIADA_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ENTIDADEASSOCIADA_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string Entidades_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Entidades_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atos Normativos.
        /// </summary>
        internal static string gridPadrao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridPadrao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Ato Normativo.
        /// </summary>
        internal static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Ato Normativo.
        /// </summary>
        internal static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do ato normativo &quot;{0}&quot;?.
        /// </summary>
        internal static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Ato Normativo.
        /// </summary>
        internal static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
    }
}
