#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\CUR\Lookups\LK_CUR_001_Componente_Curricular\_CustomView.cshtml"
    using SMC.Academico.UI.Mvc.Areas.CUR.Lookups;
    
    #line default
    #line hidden
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    
    #line 1 "..\..\Areas\CUR\Lookups\LK_CUR_001_Componente_Curricular\_CustomView.cshtml"
    using SMC.Framework.UI.Mvc.Html.DataSelector;
    
    #line default
    #line hidden
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CUR/Lookups/LK_CUR_001_Componente_Curricular/_CustomView.cshtml")]
    public partial class _Areas_CUR_Lookups_LK_CUR_001_Componente_Curricular__CustomView_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<dynamic>
    {
        public _Areas_CUR_Lookups_LK_CUR_001_Componente_Curricular__CustomView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Areas\CUR\Lookups\LK_CUR_001_Componente_Curricular\_CustomView.cshtml"
  
    bool isMultiSelect = ViewBag.DataSelectorMultipleSelect;
    object s = ViewBag.DataSelectorSelectedValue;
    var guidJanela = Guid.NewGuid().ToString();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Areas\CUR\Lookups\LK_CUR_001_Componente_Curricular\_CustomView.cshtml"
Write(Smc.DataSelectorGrid(s, isMultiSelect, x => Smc.Button(SMCMvcConsts.MODAL_BEHAVIOR_OPEN)
            .Attribute(SMCMvcConsts.MODAL_ID, guidJanela)
            .Attribute(SMCMvcConsts.MODAL_TITLE, Smc.GetUIResource("Title_Modal_Consulta_Detalhes_Componente_Curricular"))
            .Ajax(isPost: false)
            .Action("VerDetalhesPartial", "ComponenteCurricular", new { @area = "CUR", @seq = (x as ComponenteCurricularLookupViewModel).Seq })
            .CssClass("smc-btn-visualizar-ico")
            .Text(Smc.GetUIResource("Botao_Consulta_Detalhes_Componente_Curricular"))
            .Tooltip(Smc.GetUIResource("Botao_Consulta_Detalhes_Componente_Curricular"))
            ));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 20 "..\..\Areas\CUR\Lookups\LK_CUR_001_Componente_Curricular\_CustomView.cshtml"
 using (Smc.ModalWindow(guidJanela)
                        .Size(SMCModalWindowSize.Largest)
                        .Button(SMCButtonBehavior.Fechar, config: bnt => bnt.DisplayMode(SMCButtonDisplayMode.TextAndIcon))
                        .Begin()) { }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
