//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CAM.Views.ProcessoSeletivo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CAM.Views.ProcessoSeletivo.App_LocalResources.Metada" +
                            "taResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CabecalhoProcessoSeletivoViewModel_SeqCampanha {
            get {
                return ResourceManager.GetString("CabecalhoProcessoSeletivoViewModel_SeqCampanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo seletivo.
        /// </summary>
        public static string ProcessoSeletivoDynamicModel {
            get {
                return ResourceManager.GetString("ProcessoSeletivoDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva vaga.
        /// </summary>
        public static string ProcessoSeletivoDynamicModel_ReservaVaga {
            get {
                return ResourceManager.GetString("ProcessoSeletivoDynamicModel_ReservaVaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo GPI.
        /// </summary>
        public static string ProcessoSeletivoDynamicModel_SeqProcessoGpi {
            get {
                return ResourceManager.GetString("ProcessoSeletivoDynamicModel_SeqProcessoGpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculo.
        /// </summary>
        public static string ProcessoSeletivoDynamicModel_SeqTipoVinculoAluno {
            get {
                return ResourceManager.GetString("ProcessoSeletivoDynamicModel_SeqTipoVinculoAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo seletivo.
        /// </summary>
        public static string ProcessoSeletivoListarDynamicModel_TipoProcessoSeletivo {
            get {
                return ResourceManager.GetString("ProcessoSeletivoListarDynamicModel_TipoProcessoSeletivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo de matrícula.
        /// </summary>
        public static string ProcessoSeletivoProcessoMatriculaViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("ProcessoSeletivoProcessoMatriculaViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poderão ser associados somente processos de matrícula da mesma unidade responsável da campanha deste processo seletivo e do ciclo letivo selecionado..
        /// </summary>
        public static string ProcessoSeletivoProcessoMatriculaViewModel_SeqProcesso_FillInstructions {
            get {
                return ResourceManager.GetString("ProcessoSeletivoProcessoMatriculaViewModel_SeqProcesso_FillInstructions", resourceCulture);
            }
        }
    }
}
