//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.Academico.Domain.Areas.CNC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.Academico.Domain.Areas.CNC.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido o cadastro de titulação associado a um curso e grau acadêmico. Defina se a titulação aplica-se somente a um determinado curso ou somente a ofertas de curso com um determinado grau acadêmico..
        /// </summary>
        internal static string MSG_Ambiguidade_CursoOuGrauAcademico {
            get {
                return ResourceManager.GetString("MSG_Ambiguidade_CursoOuGrauAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique o total da carga horária integralizada x carga horária do currículo..
        /// </summary>
        internal static string MSG_Carga_Horaria_Datas_Historico {
            get {
                return ResourceManager.GetString("MSG_Carga_Horaria_Datas_Historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico escolar invalidado mediante a emissão de nova via do histórico, conforme a solicitação através do protocolo {0}..
        /// </summary>
        internal static string MSG_Historico_Escolar_Invalidado {
            get {
                return ResourceManager.GetString("MSG_Historico_Escolar_Invalidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;O Reitor da Pontifícia Universidade Católica de Minas Gerais, &lt;/p&gt;
        ///&lt;p&gt;tendo em vista a conclusão do curso &lt;b&gt;{0}&lt;/b&gt;,&lt;/p&gt;
        ///&lt;p&gt;na data &lt;b&gt;{1}&lt;/b&gt;, e a colação de grau na data de &lt;b&gt;{2}&lt;/b&gt;,
        ///&lt;p&gt;confere o título de &lt;b&gt;{3}&lt;/b&gt; a&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;{4}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;nacionalidade &lt;b&gt;{5}&lt;/b&gt;, natural de &lt;b&gt;{6}&lt;/b&gt;, nascimento em &lt;b&gt;{7}&lt;/b&gt;,&lt;/p&gt;
        ///&lt;p&gt;documento de identificação &lt;b&gt;{8}&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string MSG_ModalInformacoesRVDDGraduacao {
            get {
                return ResourceManager.GetString("MSG_ModalInformacoesRVDDGraduacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível prosseguir o cadastro. Verifique se a titulação está associada a um curso ou um grau acadêmico..
        /// </summary>
        internal static string MSG_Obrigatoriedade_CursoOuGrauAcademico {
            get {
                return ResourceManager.GetString("MSG_Obrigatoriedade_CursoOuGrauAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique a ordem cronológica das datas de ingresso x conclusão x colação..
        /// </summary>
        internal static string MSG_Ordem_Cronologica_Datas_Historico {
            get {
                return ResourceManager.GetString("MSG_Ordem_Cronologica_Datas_Historico", resourceCulture);
            }
        }
    }
}
