//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Aluno.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Aluno.App_GlobalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string Botao_Abrir_Solicitacao {
            get {
                return ResourceManager.GetString("Botao_Abrir_Solicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string Botao_Abrir_Solicitacao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Abrir_Solicitacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Botao_Cancelarprocesso {
            get {
                return ResourceManager.GetString("Botao_Cancelarprocesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar matrícula.
        /// </summary>
        internal static string Botao_Concluirprocesso {
            get {
                return ResourceManager.GetString("Botao_Concluirprocesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Botao_Deslogar {
            get {
                return ResourceManager.GetString("Botao_Deslogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais informações.
        /// </summary>
        internal static string Botao_Divisao_Turma {
            get {
                return ResourceManager.GetString("Botao_Divisao_Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Botao_DownloadMaterial {
            get {
                return ResourceManager.GetString("Botao_DownloadMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download de material didático.
        /// </summary>
        internal static string Botao_DownloadMaterial_Tooltip {
            get {
                return ResourceManager.GetString("Botao_DownloadMaterial_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string Botao_Editar {
            get {
                return ResourceManager.GetString("Botao_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string Botao_Editar_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Editar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar histórico escolar.
        /// </summary>
        internal static string Botao_Historico_Escolar_Integralizacao {
            get {
                return ResourceManager.GetString("Botao_Historico_Escolar_Integralizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar integralização curricular.
        /// </summary>
        internal static string Botao_Integralizacao_Curricular {
            get {
                return ResourceManager.GetString("Botao_Integralizacao_Curricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar integralização curricular.
        /// </summary>
        internal static string Botao_Integralizacao_Curricular_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Integralizacao_Curricular_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página anterior.
        /// </summary>
        internal static string Botao_Navegacao_Anterior {
            get {
                return ResourceManager.GetString("Botao_Navegacao_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima página.
        /// </summary>
        internal static string Botao_Navegacao_Proximo {
            get {
                return ResourceManager.GetString("Botao_Navegacao_Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Botao_Sairprocesso {
            get {
                return ResourceManager.GetString("Botao_Sairprocesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string Botao_Selecionar {
            get {
                return ResourceManager.GetString("Botao_Selecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar instituição.
        /// </summary>
        internal static string Botao_SelecionarInstituicao {
            get {
                return ResourceManager.GetString("Botao_SelecionarInstituicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar instituição.
        /// </summary>
        internal static string Botao_SelecionarInstituicao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_SelecionarInstituicao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Botao_Visualizar_Solicitacao {
            get {
                return ResourceManager.GetString("Botao_Visualizar_Solicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Botao_Visualizar_Solicitacao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Visualizar_Solicitacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor (R$) - Boleto.
        /// </summary>
        internal static string Class_ValorBoletoFormatado {
            get {
                return ResourceManager.GetString("Class_ValorBoletoFormatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professores.
        /// </summary>
        internal static string Colaboradores_Professores_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Colaboradores_Professores_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga horária.
        /// </summary>
        internal static string Colaboradores_Professores_Detalhe_Titulo_CargaHoraria {
            get {
                return ResourceManager.GetString("Colaboradores_Professores_Detalhe_Titulo_CargaHoraria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Colaboradores_Professores_Detalhe_Titulo_Tema {
            get {
                return ResourceManager.GetString("Colaboradores_Professores_Detalhe_Titulo_Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes curriculares.
        /// </summary>
        internal static string ComponentesCurriculares_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ComponentesCurriculares_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do professor.
        /// </summary>
        internal static string DADOSDOPROFESSOR_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DADOSDOPROFESSOR_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos de diferentes cursos poderão cursar turmas compartilhadas..
        /// </summary>
        internal static string DescricaoTipoTurma_FillInstructions {
            get {
                return ResourceManager.GetString("DescricaoTipoTurma_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma desfazer a exclusão da atividade acadêmica &quot;{0}&quot; ?.
        /// </summary>
        internal static string Desfazer_Excluir_Atividade_Selecionado {
            get {
                return ResourceManager.GetString("Desfazer_Excluir_Atividade_Selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma desfazer a exclusão da turma &quot;{0}&quot; ?.
        /// </summary>
        internal static string Desfazer_Excluir_Turma_Selecionado {
            get {
                return ResourceManager.GetString("Desfazer_Excluir_Turma_Selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        internal static string Detalhe_Label_TotalCargaHorariaHoras {
            get {
                return ResourceManager.GetString("Detalhe_Label_TotalCargaHorariaHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas Aula.
        /// </summary>
        internal static string Detalhe_Label_TotalCargaHorariaHorasAula {
            get {
                return ResourceManager.GetString("Detalhe_Label_TotalCargaHorariaHorasAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades acadêmicas.
        /// </summary>
        internal static string Fieldset_Modal_SelecaoAtividade_Lista_Titulo {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoAtividade_Lista_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Botao_Pesquisar {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Botao_Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir somente turma pertencente ao currículo.
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Campo_Curriculo {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Campo_Curriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codificação.
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Campo_Divisao {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Campo_Divisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turma.
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Campo_Turma {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Campo_Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vagas: .
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Campo_Vagas {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Campo_Vagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turmas ofertadas - .
        /// </summary>
        internal static string Fieldset_Modal_SelecaoTurma_Lista_Titulo {
            get {
                return ResourceManager.GetString("Fieldset_Modal_SelecaoTurma_Lista_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negociação de Parcelas.
        /// </summary>
        internal static string fsDadosFinanceirosAluno_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fsDadosFinanceirosAluno_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliações.
        /// </summary>
        internal static string GridAvalicaoDivisaoTurma_Grid_Titulo {
            get {
                return ResourceManager.GetString("GridAvalicaoDivisaoTurma_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliações.
        /// </summary>
        internal static string GridAvalicaoTurma_Grid_Titulo {
            get {
                return ResourceManager.GetString("GridAvalicaoTurma_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo da negociação.
        /// </summary>
        internal static string gridParcelasSelecionadas_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridParcelasSelecionadas_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situações.
        /// </summary>
        internal static string GridSituacoes_Grid_Titulo {
            get {
                return ResourceManager.GetString("GridSituacoes_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos curriculares.
        /// </summary>
        internal static string GruposCurriculares_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("GruposCurriculares_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As atividades acadêmicas que não podem ser selecionadas possuem pré-requisitos que você ainda não cumpriu..
        /// </summary>
        internal static string Informativo_Atividade_Existe_PreRequisito {
            get {
                return ResourceManager.GetString("Informativo_Atividade_Existe_PreRequisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem itens da sua solicitação de matrícula que foram indeferidos, cancelados, aprovados ou dispensados. Clique em “Exibir itens” para visualizá-los..
        /// </summary>
        internal static string Informativo_Turma_Atividade {
            get {
                return ResourceManager.GetString("Informativo_Turma_Atividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você foi convocado para a(s) turma(s) abaixo. Nesta etapa do processo, não é possível realizar alterações na solicitação de matrícula. Favor prosseguir e, caso queira, requerer a alteração na 2ª Etapa - Efetivação de Matrícula..
        /// </summary>
        internal static string Informativo_Turma_Convocado {
            get {
                return ResourceManager.GetString("Informativo_Turma_Convocado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As turmas que não podem ser selecionadas possuem pré-requisitos que você ainda não cumpriu..
        /// </summary>
        internal static string Informativo_Turma_Existe_PreRequisito {
            get {
                return ResourceManager.GetString("Informativo_Turma_Existe_PreRequisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para atualizar o resultado da pesquisa, de acordo com os filtros informados abaixo, clique no botão &quot;Pesquisar&quot;..
        /// </summary>
        internal static string Informativo_Turma_Pesquisar {
            get {
                return ResourceManager.GetString("Informativo_Turma_Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível prosseguir o Processo de Matrícula, pois o(s) item(ns) da sua solicitação foram cancelados. Favor entrar em contato com a secretaria do programa..
        /// </summary>
        internal static string Informativo_Turma_Todas_Canceladas {
            get {
                return ResourceManager.GetString("Informativo_Turma_Todas_Canceladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do item cursado.
        /// </summary>
        internal static string ITEMCURSADO_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ITEMCURSADO_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ementa.
        /// </summary>
        internal static string Label_Componente_Curricular_Ementa_Fieldset {
            get {
                return ResourceManager.GetString("Label_Componente_Curricular_Ementa_Fieldset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma ementa registrada para este componente curricular..
        /// </summary>
        internal static string Label_Componente_Curricular_Ementa_SemRegistro {
            get {
                return ResourceManager.GetString("Label_Componente_Curricular_Ementa_SemRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Específico para bolsistas:.
        /// </summary>
        internal static string Label_EspecificoBolsista {
            get {
                return ResourceManager.GetString("Label_EspecificoBolsista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Específico quando há a condição:.
        /// </summary>
        internal static string Label_EspecificoCondicao {
            get {
                return ResourceManager.GetString("Label_EspecificoCondicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .E o mesmo está associado nas seguintes divisões curriculares e com as seguintes configurações:.
        /// </summary>
        internal static string Label_EspecificoDivisoes {
            get {
                return ResourceManager.GetString("Label_EspecificoDivisoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Específico para a formação:.
        /// </summary>
        internal static string Label_EspecificoFormacao {
            get {
                return ResourceManager.GetString("Label_EspecificoFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse grupo curricular possui a seguinte configuração:.
        /// </summary>
        internal static string Label_EspecificoGrupo {
            get {
                return ResourceManager.GetString("Label_EspecificoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O componente curricular foi cursado anteriormente:.
        /// </summary>
        internal static string Label_Historico_Escolar_Integralizacao_Cursados {
            get {
                return ResourceManager.GetString("Label_Historico_Escolar_Integralizacao_Cursados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente curricular dispensado, através do deferimento da solicitação:.
        /// </summary>
        internal static string Label_Historico_Escolar_Integralizacao_Dispensa {
            get {
                return ResourceManager.GetString("Label_Historico_Escolar_Integralizacao_Dispensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi identificado para o {0} a associação de Matriz Curricular ou, registros no Histórico Escolar e/ou Plano de Estudos..
        /// </summary>
        internal static string Label_Lista_Integralizacao_SemRegistro {
            get {
                return ResourceManager.GetString("Label_Lista_Integralizacao_SemRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro retornado..
        /// </summary>
        internal static string Label_Nenhum_Registro {
            get {
                return ResourceManager.GetString("Label_Nenhum_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma atividade acadêmica selecionada.
        /// </summary>
        internal static string Label_Nenhum_Registro_Atividade_Selecionada {
            get {
                return ResourceManager.GetString("Label_Nenhum_Registro_Atividade_Selecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum colaborador disponível..
        /// </summary>
        internal static string Label_Nenhum_Registro_Colaborador {
            get {
                return ResourceManager.GetString("Label_Nenhum_Registro_Colaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma turma disponível..
        /// </summary>
        internal static string Label_Nenhum_Registro_Turma {
            get {
                return ResourceManager.GetString("Label_Nenhum_Registro_Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma turma selecionada..
        /// </summary>
        internal static string Label_Nenhum_Registro_Turma_Selecionada {
            get {
                return ResourceManager.GetString("Label_Nenhum_Registro_Turma_Selecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string Label_Observacao {
            get {
                return ResourceManager.GetString("Label_Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string Label_Observacoes {
            get {
                return ResourceManager.GetString("Label_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo.
        /// </summary>
        internal static string Label_Protocolo {
            get {
                return ResourceManager.GetString("Label_Protocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string Label_Selecionar {
            get {
                return ResourceManager.GetString("Label_Selecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string Label_Voltar {
            get {
                return ResourceManager.GetString("Label_Voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTI - Gerência de Tecnologia da Informação.
        /// </summary>
        internal static string Layout_Rodape_Mensagem_SMC {
            get {
                return ResourceManager.GetString("Layout_Rodape_Mensagem_SMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        internal static string Layout_Texto_Aguarde {
            get {
                return ResourceManager.GetString("Layout_Texto_Aguarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} - Todos direitos reservados..
        /// </summary>
        internal static string Layout_Texto_Copyright {
            get {
                return ResourceManager.GetString("Layout_Texto_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerência de Tecnologia da Informação.
        /// </summary>
        internal static string Layout_Titulo_Logotipo_GTI {
            get {
                return ResourceManager.GetString("Layout_Titulo_Logotipo_GTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociedade Mineira de Cultura.
        /// </summary>
        internal static string Layout_Titulo_Logotipo_SMC {
            get {
                return ResourceManager.GetString("Layout_Titulo_Logotipo_SMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades acadêmicas.
        /// </summary>
        internal static string listaAtividades_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("listaAtividades_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turmas.
        /// </summary>
        internal static string listaTurmas_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("listaTurmas_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A consulta completa com todos os dados da solicitação de serviço está disponível através da Central de Solicitações..
        /// </summary>
        internal static string Modal_Solicitacao_Administrativo_Informativo {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Administrativo_Informativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Identificacao {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Identificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Justificativa {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação atual.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Situacao {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Solicitacao {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Solicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação - Solicitação atualizada.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Solicitacao_Atualizada {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Solicitacao_Atualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação - Solicitação original.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Solicitacao_Original {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Solicitacao_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação.
        /// </summary>
        internal static string Modal_Solicitacao_Fieldset_Solicitacao_Servico {
            get {
                return ResourceManager.GetString("Modal_Solicitacao_Fieldset_Solicitacao_Servico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Integralização Curricular.
        /// </summary>
        internal static string Modal_Title_Integralizacao_Curricular {
            get {
                return ResourceManager.GetString("Modal_Title_Integralizacao_Curricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavras-chave.
        /// </summary>
        internal static string PalavrasChave_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("PalavrasChave_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisões de turma.
        /// </summary>
        internal static string ParametroDivisoes_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ParametroDivisoes_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGA.
        /// </summary>
        internal static string SiglaAplicacao {
            get {
                return ResourceManager.GetString("SiglaAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo {0} de {1}.
        /// </summary>
        internal static string Texto_Passo_Atual {
            get {
                return ResourceManager.GetString("Texto_Passo_Atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Ementa.
        /// </summary>
        internal static string Title_Componente_Curricular_Ementa {
            get {
                return ResourceManager.GetString("Title_Componente_Curricular_Ementa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes curriculares.
        /// </summary>
        internal static string Title_Componentes_Curricular_Cursados {
            get {
                return ResourceManager.GetString("Title_Componentes_Curricular_Cursados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer Exclusão de Atividade Acadêmica.
        /// </summary>
        internal static string Title_Desfazer_Excluir_Atividade_Selecionado {
            get {
                return ResourceManager.GetString("Title_Desfazer_Excluir_Atividade_Selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer Exclusão de Turma.
        /// </summary>
        internal static string Title_Desfazer_Excluir_Turma_Selecionado {
            get {
                return ResourceManager.GetString("Title_Desfazer_Excluir_Turma_Selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Divisão de Turma.
        /// </summary>
        internal static string Title_Divisao_Turma {
            get {
                return ResourceManager.GetString("Title_Divisao_Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Histórico Escolar.
        /// </summary>
        internal static string Title_Historico_Escolar_Integralizacao {
            get {
                return ResourceManager.GetString("Title_Historico_Escolar_Integralizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Solicitação de Serviço.
        /// </summary>
        internal static string Title_Modal_Solicitacao_Servico_Simplificado {
            get {
                return ResourceManager.GetString("Title_Modal_Solicitacao_Servico_Simplificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Estudo.
        /// </summary>
        internal static string Title_Modal_Visualizar_PlanoEnsino {
            get {
                return ResourceManager.GetString("Title_Modal_Visualizar_PlanoEnsino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens Indeferidos e Cancelados.
        /// </summary>
        internal static string Title_Modal_Visualizar_PlanoEnsinoCancelado {
            get {
                return ResourceManager.GetString("Title_Modal_Visualizar_PlanoEnsinoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Horária.
        /// </summary>
        internal static string Titulo_Label_TotalCargaHoraria {
            get {
                return ResourceManager.GetString("Titulo_Label_TotalCargaHoraria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos.
        /// </summary>
        internal static string Titulo_Label_TotalCreditos {
            get {
                return ResourceManager.GetString("Titulo_Label_TotalCreditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação dos componentes curriculares.
        /// </summary>
        internal static string Titulo_Legenda_SituacaoComponenteIntegralizacao {
            get {
                return ResourceManager.GetString("Titulo_Legenda_SituacaoComponenteIntegralizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de solicitação.
        /// </summary>
        internal static string Titulo_Legenda_SituacaoItemMatricula {
            get {
                return ResourceManager.GetString("Titulo_Legenda_SituacaoItemMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertence ao currículo.
        /// </summary>
        internal static string Titulo_Legenda_TurmaOfertaMatricula {
            get {
                return ResourceManager.GetString("Titulo_Legenda_TurmaOfertaMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais informações.
        /// </summary>
        internal static string Tooltip_Divisao_Turma {
            get {
                return ResourceManager.GetString("Tooltip_Divisao_Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de itens cursados para dispensa.
        /// </summary>
        internal static string TotalItensCursados_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("TotalItensCursados_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de itens solicitados para dispensa.
        /// </summary>
        internal static string TotalItensDispensa_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("TotalItensDispensa_Fieldset_Legenda", resourceCulture);
            }
        }
    }
}
