//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.OFC.Views.OfertaCursoCicloLetivo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.OFC.Views.OfertaCursoCicloLetivo.App_LocalResources." +
                            "UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize e selecione uma ou mais localidades.
        /// </summary>
        internal static string _AssociarLocalidade_Texto_Selecione_Localidades {
            get {
                return ResourceManager.GetString("_AssociarLocalidade_Texto_Selecione_Localidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize e selecione um ou mais polos.
        /// </summary>
        internal static string _AssociarPolo_Texto_Selecione_Polos {
            get {
                return ResourceManager.GetString("_AssociarPolo_Texto_Selecione_Polos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso/Unidade/Turno.
        /// </summary>
        internal static string _BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarCursoUnidadeTurno_Label {
            get {
                return ResourceManager.GetString("_BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarCursoUnidadeTurno" +
                        "_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Localidade.
        /// </summary>
        internal static string _BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarLocalidade_Label {
            get {
                return ResourceManager.GetString("_BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarLocalidade_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Polo.
        /// </summary>
        internal static string _BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarPolo_Label {
            get {
                return ResourceManager.GetString("_BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_AssociarPolo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string _BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_Editar_Label {
            get {
                return ResourceManager.GetString("_BotaoConfigurarOfertaCursoCicloLetivo_Botao_Configurar_Editar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso/Unidade/Turno.
        /// </summary>
        internal static string _ListarAssociacaoCursoUnidadeTurno_Editar_Associacao_Modal_Title {
            get {
                return ResourceManager.GetString("_ListarAssociacaoCursoUnidadeTurno_Editar_Associacao_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da associação curso/unidade &quot;{0}/{1}&quot;?.
        /// </summary>
        internal static string _ListarAssociacaoCursoUnidadeTurno_Exclusao_Curso_Unidade_Turno_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarAssociacaoCursoUnidadeTurno_Exclusao_Curso_Unidade_Turno_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Associação de Curso/Unidade.
        /// </summary>
        internal static string _ListarAssociacaoCursoUnidadeTurno_Exclusao_Curso_Unidade_Turno_Title {
            get {
                return ResourceManager.GetString("_ListarAssociacaoCursoUnidadeTurno_Exclusao_Curso_Unidade_Turno_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos associados.
        /// </summary>
        internal static string _ListarAssociacaoCursoUnidadeTurno_gridAssociacaoCursoUnidadeTurno_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarAssociacaoCursoUnidadeTurno_gridAssociacaoCursoUnidadeTurno_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos/Unidades/Turnos.
        /// </summary>
        internal static string _ListarAssociacaoCursoUnidadeTurnoLote_gridAssociacaoCursoUnidadeTurnoLote_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarAssociacaoCursoUnidadeTurnoLote_gridAssociacaoCursoUnidadeTurnoLote_Grid_T" +
                        "itulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da localidade &quot;{0}&quot;?.
        /// </summary>
        internal static string _ListarAssociacaoLocalidade_Exclusao_Associacao_Localidade_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarAssociacaoLocalidade_Exclusao_Associacao_Localidade_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Localidade.
        /// </summary>
        internal static string _ListarAssociacaoLocalidade_Exclusao_Associacao_Localidade_Title {
            get {
                return ResourceManager.GetString("_ListarAssociacaoLocalidade_Exclusao_Associacao_Localidade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades.
        /// </summary>
        internal static string _ListarAssociacaoLocalidade_gridAssociacaoLocalidade_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarAssociacaoLocalidade_gridAssociacaoLocalidade_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do polo &quot;{0}&quot;?.
        /// </summary>
        internal static string _ListarAssociacaoPolo_Exclusao_Associacao_Polo_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarAssociacaoPolo_Exclusao_Associacao_Polo_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Polo.
        /// </summary>
        internal static string _ListarAssociacaoPolo_Exclusao_Associacao_Polo_Title {
            get {
                return ResourceManager.GetString("_ListarAssociacaoPolo_Exclusao_Associacao_Polo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polos.
        /// </summary>
        internal static string _ListarAssociacaoPolo_gridAssociacaoPolo_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarAssociacaoPolo_gridAssociacaoPolo_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da oferta de curso por ciclo letivo &quot;{0}&quot;?.
        /// </summary>
        internal static string _ListarCicloLetivo_Exclusao_Ciclo_Letivo_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarCicloLetivo_Exclusao_Ciclo_Letivo_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Oferta de Curso por Ciclo Letivo.
        /// </summary>
        internal static string _ListarCicloLetivo_Exclusao_Ciclo_Letivo_Title {
            get {
                return ResourceManager.GetString("_ListarCicloLetivo_Exclusao_Ciclo_Letivo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de Cursos por Ciclo Letivo.
        /// </summary>
        internal static string _ListarCicloLetivo_gridCicloLetivo_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarCicloLetivo_gridCicloLetivo_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da oferta &quot;{0}&quot;?.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_Exclusao_Oferta_Curso_Ciclo_Letivo_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_Exclusao_Oferta_Curso_Ciclo_Letivo_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Oferta de Curso por Ciclo Letivo.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_Exclusao_Oferta_Curso_Ciclo_Letivo_Title {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_Exclusao_Oferta_Curso_Ciclo_Letivo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas Cursos por Ciclo Letivo.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_gridOfertaCursoCicloLetivo_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_gridOfertaCursoCicloLetivo_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso/Unidade/Turno.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_Menu_Configurar_Associar_Curso_Unidade_Turno_Label {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_Menu_Configurar_Associar_Curso_Unidade_Turno_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Localidade.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_Menu_Configurar_Configurar_Associar_Localidade_Label {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_Menu_Configurar_Configurar_Associar_Localidade_Labe" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Polo.
        /// </summary>
        internal static string _ListarOfertaCursoCicloLetivo_Menu_Configurar_Configurar_Associar_Polo_Label {
            get {
                return ResourceManager.GetString("_ListarOfertaCursoCicloLetivo_Menu_Configurar_Configurar_Associar_Polo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação em Lote.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_AssociacaoLote {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_AssociacaoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação Única.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_AssociacaoUnica {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_AssociacaoUnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar curso/Unidade/Turno.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_Botao_AssociarCursoUnidadeTurno {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_Botao_AssociarCursoUnidadeTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar curso / Unidade / Turno.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_Botao_AssociarCursoUnidadeTurno_Tooltip {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_Botao_AssociarCursoUnidadeTurno_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_Botao_Salvar {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso/Unidade/Turno.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_Incluir_Associacao_Modal_Title {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_Incluir_Associacao_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso / Unidade / Turno.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurno_Title {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurno_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o período em que a oferta será realizada. Lembre-se: as datas informadas serão aplicadas a todos os cursos selecionados..
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurnoLote_Texto_Informativo_Campos_Periodo_Oferta {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurnoLote_Texto_Informativo_Campos_Periodo_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Curso / Unidade / Turno em Lote.
        /// </summary>
        internal static string AssociacaoCursoUnidadeTurnoLote_Title {
            get {
                return ResourceManager.GetString("AssociacaoCursoUnidadeTurnoLote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Localidade.
        /// </summary>
        internal static string AssociacaoLocalidade_Associar_Localidade_Modal_Title {
            get {
                return ResourceManager.GetString("AssociacaoLocalidade_Associar_Localidade_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar localidade.
        /// </summary>
        internal static string AssociacaoLocalidade_Botao_Open {
            get {
                return ResourceManager.GetString("AssociacaoLocalidade_Botao_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar localidade.
        /// </summary>
        internal static string AssociacaoLocalidade_Botao_Open_Tooltip {
            get {
                return ResourceManager.GetString("AssociacaoLocalidade_Botao_Open_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar.
        /// </summary>
        internal static string AssociacaoLocalidade_Botao_Salvar {
            get {
                return ResourceManager.GetString("AssociacaoLocalidade_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Localidade.
        /// </summary>
        internal static string AssociacaoLocalidade_Title {
            get {
                return ResourceManager.GetString("AssociacaoLocalidade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Polo.
        /// </summary>
        internal static string AssociacaoPolo_Associar_Polo_Modal_Title {
            get {
                return ResourceManager.GetString("AssociacaoPolo_Associar_Polo_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar polo.
        /// </summary>
        internal static string AssociacaoPolo_Botao_Open {
            get {
                return ResourceManager.GetString("AssociacaoPolo_Botao_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar polo.
        /// </summary>
        internal static string AssociacaoPolo_Botao_Open_Tooltip {
            get {
                return ResourceManager.GetString("AssociacaoPolo_Botao_Open_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar.
        /// </summary>
        internal static string AssociacaoPolo_Botao_Salvar {
            get {
                return ResourceManager.GetString("AssociacaoPolo_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Polo.
        /// </summary>
        internal static string AssociacaoPolo_Title {
            get {
                return ResourceManager.GetString("AssociacaoPolo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Oferta de Curso por Ciclo Letivo.
        /// </summary>
        internal static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Oferta de Curso por Ciclo Letivo.
        /// </summary>
        internal static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova oferta de curso.
        /// </summary>
        internal static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova oferta de curso por ciclo letivo.
        /// </summary>
        internal static string Index_Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Index_Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Oferta de Curso por Ciclo Letivo.
        /// </summary>
        internal static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
    }
}
