//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CSO.Views.Programa.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CSO.Views.Programa.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Gerais.
        /// </summary>
        public static string Aba_Title_0 {
            get {
                return ResourceManager.GetString("Aba_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificações.
        /// </summary>
        public static string Aba_Title_1 {
            get {
                return ResourceManager.GetString("Aba_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Contato.
        /// </summary>
        public static string Aba_Title_2 {
            get {
                return ResourceManager.GetString("Aba_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ato Normativo.
        /// </summary>
        public static string Aba_Title_3 {
            get {
                return ResourceManager.GetString("Aba_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação.
        /// </summary>
        public static string Botao_AlterarSituacaoPrograma {
            get {
                return ResourceManager.GetString("Botao_AlterarSituacaoPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação.
        /// </summary>
        public static string Botao_AlterarSituacaoPrograma_Tooltip {
            get {
                return ResourceManager.GetString("Botao_AlterarSituacaoPrograma_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar curso.
        /// </summary>
        public static string Botao_CursosPrograma {
            get {
                return ResourceManager.GetString("Botao_CursosPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar curso.
        /// </summary>
        public static string Botao_CursosPrograma_Tooltip {
            get {
                return ResourceManager.GetString("Botao_CursosPrograma_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar formação específica.
        /// </summary>
        public static string Botao_FormacoesEspecificasPrograma {
            get {
                return ResourceManager.GetString("Botao_FormacoesEspecificasPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar formação específica.
        /// </summary>
        public static string Botao_FormacoesEspecificasPrograma_Tooltip {
            get {
                return ResourceManager.GetString("Botao_FormacoesEspecificasPrograma_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo programa.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo programa.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar proposta.
        /// </summary>
        public static string Botao_PropostasPrograma {
            get {
                return ResourceManager.GetString("Botao_PropostasPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar proposta.
        /// </summary>
        public static string Botao_PropostasPrograma_Tooltip {
            get {
                return ResourceManager.GetString("Botao_PropostasPrograma_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Ato Normativo.
        /// </summary>
        public static string Botao_Visualizar_Ato {
            get {
                return ResourceManager.GetString("Botao_Visualizar_Ato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações em outros idiomas.
        /// </summary>
        public static string DadosOutrosIdiomas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("DadosOutrosIdiomas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar.
        /// </summary>
        public static string DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Programa.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string fieldsetConfirmacao_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetConfirmacao_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string fieldsetCurso_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCurso_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta de Curso por Localidade.
        /// </summary>
        public static string fieldsetCursoOfertaLocalidade_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetCursoOfertaLocalidade_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Programa.
        /// </summary>
        public static string GRUPO_Alterar {
            get {
                return ResourceManager.GetString("GRUPO_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação CAPES.
        /// </summary>
        public static string HistoricoNotas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("HistoricoNotas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Programa.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Programa.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        public static string Label_Cursos {
            get {
                return ResourceManager.GetString("Label_Cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do programa &quot;{0}&quot;?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Programa.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicação da formação específica do programa realizada com sucesso..
        /// </summary>
        public static string MensagemSucessoReplicarFormacaoEspecificaPrograma {
            get {
                return ResourceManager.GetString("MensagemSucessoReplicarFormacaoEspecificaPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a replicação da formação {0} para os seguintes Cursos e Ofertas de Curso por Localidade?.
        /// </summary>
        public static string MSG_MensagemInformativaConfirmacao {
            get {
                return ResourceManager.GetString("MSG_MensagemInformativaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione para quais cursos a formação {0} deverá ser replicada..
        /// </summary>
        public static string MSG_MensagemInformativaCurso {
            get {
                return ResourceManager.GetString("MSG_MensagemInformativaCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione para quais Ofertas de Curso por Localidade, a formação {0} deverá ser replicada..
        /// </summary>
        public static string MSG_MensagemInformativaCursoOfertaLocalidade {
            get {
                return ResourceManager.GetString("MSG_MensagemInformativaCursoOfertaLocalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a titulação que a formação {0}, concede por curso..
        /// </summary>
        public static string MSG_MensagemInformativaTitulacao {
            get {
                return ResourceManager.GetString("MSG_MensagemInformativaTitulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicar Formação Específica de Programa.
        /// </summary>
        public static string ReplicarFormacaoEspecificaPrograma_Title {
            get {
                return ResourceManager.GetString("ReplicarFormacaoEspecificaPrograma_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string SITUACAOENTIDADE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("SITUACAOENTIDADE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de autorização para publicação do trabalho no BDP.
        /// </summary>
        public static string TiposAutorizacaoBdp_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("TiposAutorizacaoBdp_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Ato Normativo.
        /// </summary>
        public static string Title_VisualizarAtoNormativo {
            get {
                return ResourceManager.GetString("Title_VisualizarAtoNormativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Wizard_Replicar_Formacao_Especifica_Programa_StepConfirmacao {
            get {
                return ResourceManager.GetString("Wizard_Replicar_Formacao_Especifica_Programa_StepConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string Wizard_Replicar_Formacao_Especifica_Programa_StepCurso {
            get {
                return ResourceManager.GetString("Wizard_Replicar_Formacao_Especifica_Programa_StepCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta de Curso por Localidade.
        /// </summary>
        public static string Wizard_Replicar_Formacao_Especifica_Programa_StepCursoOfertaLocalidade {
            get {
                return ResourceManager.GetString("Wizard_Replicar_Formacao_Especifica_Programa_StepCursoOfertaLocalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulação.
        /// </summary>
        public static string Wizard_Replicar_Formacao_Especifica_Programa_StepTitulacao {
            get {
                return ResourceManager.GetString("Wizard_Replicar_Formacao_Especifica_Programa_StepTitulacao", resourceCulture);
            }
        }
    }
}
