//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.PES.Views.Funcionario.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.PES.Views.Funcionario.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string Aba_Title_0 {
            get {
                return ResourceManager.GetString("Aba_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos.
        /// </summary>
        public static string Aba_Title_1 {
            get {
                return ResourceManager.GetString("Aba_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar vínculo.
        /// </summary>
        public static string Botao_CadastroVinculoColaborador {
            get {
                return ResourceManager.GetString("Botao_CadastroVinculoColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar vínculo.
        /// </summary>
        public static string Botao_CadastroVinculoColaborador_Tooltip {
            get {
                return ResourceManager.GetString("Botao_CadastroVinculoColaborador_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Vínculo.
        /// </summary>
        public static string Botao_CadastroVinculoFuncionario {
            get {
                return ResourceManager.GetString("Botao_CadastroVinculoFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo funcionário.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo funcionário.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos.
        /// </summary>
        public static string Contatos_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("Contatos_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string ContatosEndereco_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ContatosEndereco_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço eletrônico.
        /// </summary>
        public static string ContatosEnderecoEletronico_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ContatosEnderecoEletronico_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string ContatosTelefone_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("ContatosTelefone_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados pessoais.
        /// </summary>
        public static string DadosPessoais_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DadosPessoais_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de motorista.
        /// </summary>
        public static string DOCUMENTOCNH_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOCNH_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidade Estrangeira.
        /// </summary>
        public static string DOCUMENTOIDENTIDADEESTRANGEIRA_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOIDENTIDADEESTRANGEIRA_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento militar.
        /// </summary>
        public static string DOCUMENTOMILITAR_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOMILITAR_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passaporte.
        /// </summary>
        public static string DOCUMENTOPASSAPORTE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOPASSAPORTE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS/PASEP.
        /// </summary>
        public static string DOCUMENTOPISPASEP_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOPISPASEP_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidade.
        /// </summary>
        public static string DOCUMENTORG_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTORG_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de eleitor.
        /// </summary>
        public static string DOCUMENTOTITULOELEITOR_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("DOCUMENTOTITULOELEITOR_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Funcionário.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Correspondência.
        /// </summary>
        public static string EnderecoCorrespondencia {
            get {
                return ResourceManager.GetString("EnderecoCorrespondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar endereço.
        /// </summary>
        public static string Enderecos_DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("Enderecos_DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar endereço.
        /// </summary>
        public static string Enderecos_DataSelector_Botao_Abrir_Tooltip {
            get {
                return ResourceManager.GetString("Enderecos_DataSelector_Botao_Abrir_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar endereço eletrônico.
        /// </summary>
        public static string EnderecosEletronicos_DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar endereço eletrônico.
        /// </summary>
        public static string EnderecosEletronicos_DataSelector_Botao_Abrir_Tooltip {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_DataSelector_Botao_Abrir_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filiação.
        /// </summary>
        public static string Filiacao_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Filiacao_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filiação.
        /// </summary>
        public static string FiliacaoReadOnly_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("FiliacaoReadOnly_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades.
        /// </summary>
        public static string FILTROATIVIDADE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("FILTROATIVIDADE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição.
        /// </summary>
        public static string FILTROINSTITUICAO_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("FILTROINSTITUICAO_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculo.
        /// </summary>
        public static string FILTROVINCULO_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("FILTROVINCULO_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        public static string gridPadrao_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridPadrao_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Funcionário.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Funcionário.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Label_Fim {
            get {
                return ResourceManager.GetString("Label_Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Label_Inicio {
            get {
                return ResourceManager.GetString("Label_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum vínculo ativo.
        /// </summary>
        public static string Label_NenhumVinculoAtivo {
            get {
                return ResourceManager.GetString("Label_NenhumVinculoAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculos ativos.
        /// </summary>
        public static string Label_VinculosAtivos {
            get {
                return ResourceManager.GetString("Label_VinculosAtivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do funcionário &quot;{0}&quot;?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Funcionário.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Início: {1:d}.
        /// </summary>
        public static string MascaraVinculo {
            get {
                return ResourceManager.GetString("MascaraVinculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Período: {1:d} à {2:d}.
        /// </summary>
        public static string MascaraVinculoPeriodo {
            get {
                return ResourceManager.GetString("MascaraVinculoPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se sim, selecione a pessoa através do botão de seleção à equerda de seu nome. Se não, selecione a opção “Nenhum resultado satisfatório”. Em seguida pressione o botão “Próximo”..
        /// </summary>
        public static string Mensagem_Step_1 {
            get {
                return ResourceManager.GetString("Mensagem_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe as instituições representadas pela pessoa que está sendo cadastrada. Em seguida, pressione o botão &quot;Próximo&quot;..
        /// </summary>
        public static string Mensagem_Step_4 {
            get {
                return ResourceManager.GetString("Mensagem_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os vínculos da pessoa que está sendo cadastrada. É necessário selecionar uma &quot;Entidade responsável&quot; para que o campo &quot;Tipo de vínculo&quot; seja habilitado. Após o preenchimento de todos os dados obrigatórios, pressione o botão &quot;Próximo&quot;..
        /// </summary>
        public static string Mensagem_Step_5 {
            get {
                return ResourceManager.GetString("Mensagem_Step_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as informações necessárias foram informadas. Confira todos dos dados da pessoa cadastrada abaixo e em seguida, pressione o botão &quot;Salvar&quot;..
        /// </summary>
        public static string Mensagem_Step_6 {
            get {
                return ResourceManager.GetString("Mensagem_Step_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta de curso por localidade/tipo de atividade.
        /// </summary>
        public static string Modal_Editar_Titulo {
            get {
                return ResourceManager.GetString("Modal_Editar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string NACIONALIDADE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("NACIONALIDADE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturalidade.
        /// </summary>
        public static string NATURALIDADE_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("NATURALIDADE_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessidades especiais.
        /// </summary>
        public static string NECESSIADESESPECIAIS_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("NECESSIADESESPECIAIS_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação.
        /// </summary>
        public static string Operacao {
            get {
                return ResourceManager.GetString("Operacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string PESQUISA_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("PESQUISA_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Profissional.
        /// </summary>
        public static string REGISTROPROFISSIONAL_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("REGISTROPROFISSIONAL_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar telefone.
        /// </summary>
        public static string Telefones_DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("Telefones_DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir/Alterar telefone.
        /// </summary>
        public static string Telefones_DataSelector_Botao_Abrir_Tooltip {
            get {
                return ResourceManager.GetString("Telefones_DataSelector_Botao_Abrir_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculo.
        /// </summary>
        public static string Vinculo_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("Vinculo_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculos.
        /// </summary>
        public static string Vinculos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Vinculos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculos.
        /// </summary>
        public static string Vinculos_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("Vinculos_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        public static string Wizard_Title_0 {
            get {
                return ResourceManager.GetString("Wizard_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string Wizard_Title_1 {
            get {
                return ResourceManager.GetString("Wizard_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos.
        /// </summary>
        public static string Wizard_Title_2 {
            get {
                return ResourceManager.GetString("Wizard_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculos.
        /// </summary>
        public static string Wizard_Title_3 {
            get {
                return ResourceManager.GetString("Wizard_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Wizard_Title_4 {
            get {
                return ResourceManager.GetString("Wizard_Title_4", resourceCulture);
            }
        }
    }
}
