//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.ALN.Views.ParceriaIntercambio.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.ALN.Views.ParceriaIntercambio.App_LocalResources.Met" +
                            "adataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string ArquivoModelo {
            get {
                return ResourceManager.GetString("ArquivoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        internal static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        internal static string DataFim {
            get {
                return ResourceManager.GetString("DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        internal static string DataInicio {
            get {
                return ResourceManager.GetString("DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de ensino logada.
        /// </summary>
        internal static string InstituicaoEnsinoLogada {
            get {
                return ResourceManager.GetString("InstituicaoEnsinoLogada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituições de ensino parceiras.
        /// </summary>
        internal static string InstituicoesExternas {
            get {
                return ResourceManager.GetString("InstituicoesExternas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da alteração.
        /// </summary>
        internal static string Justificativa {
            get {
                return ResourceManager.GetString("Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parceria de intercâmbio.
        /// </summary>
        internal static string ParceriaIntercambioDynamicModel {
            get {
                return ResourceManager.GetString("ParceriaIntercambioDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa?.
        /// </summary>
        internal static string ParceriaIntercambioFiltroDynamicModel_Ativo {
            get {
                return ResourceManager.GetString("ParceriaIntercambioFiltroDynamicModel_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa?.
        /// </summary>
        internal static string ParceriaIntercambioInstituicaoExternaViewModel_Ativo {
            get {
                return ResourceManager.GetString("ParceriaIntercambioInstituicaoExternaViewModel_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de Ensino Externa.
        /// </summary>
        internal static string ParceriaIntercambioInstituicaoExternaViewModel_Nome {
            get {
                return ResourceManager.GetString("ParceriaIntercambioInstituicaoExternaViewModel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa?.
        /// </summary>
        internal static string ParceriaIntercambioListarDynamicModel_Ativo {
            get {
                return ResourceManager.GetString("ParceriaIntercambioListarDynamicModel_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da alteração.
        /// </summary>
        internal static string ParceriaIntercambioVigenciaViewModel_Justificativa {
            get {
                return ResourceManager.GetString("ParceriaIntercambioVigenciaViewModel_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui anexo?.
        /// </summary>
        internal static string PossuiAnexo {
            get {
                return ResourceManager.GetString("PossuiAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em processo de renovação.
        /// </summary>
        internal static string ProcessoNegociacao {
            get {
                return ResourceManager.GetString("ProcessoNegociacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de ensino externa.
        /// </summary>
        internal static string SeqInstituicaoExterna {
            get {
                return ResourceManager.GetString("SeqInstituicaoExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de termo.
        /// </summary>
        internal static string SeqTipoTermoIntercambio {
            get {
                return ResourceManager.GetString("SeqTipoTermoIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de parceria.
        /// </summary>
        internal static string TipoParceriaIntercambio {
            get {
                return ResourceManager.GetString("TipoParceriaIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de termo.
        /// </summary>
        internal static string TiposTermo {
            get {
                return ResourceManager.GetString("TiposTermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de termos.
        /// </summary>
        internal static string TotalTermos {
            get {
                return ResourceManager.GetString("TotalTermos", resourceCulture);
            }
        }
    }
}
