namespace SMC.Academico.Common.Areas.CNC.Constants
{
    public static class TOKEN_TIPO_DOCUMENTO_EMISSAO_DIPLOMA
    {
        public const string HISTORICO_ESCOLAR = "HISTORICO_ESCOLAR";
        public const string COMPROVANTE_ESTAGIO_CURRICULAR = "COMPROVANTE_ESTAGIO_CURRICULAR";
        public const string PROVA_COLACAO_GRAU = "PROVA_COLACAO_GRAU";
        public const string CERTIFICADO_DE_CONCLUSAO_DO_ENSINO_MEDIO_FRENTE_E_VERSO = "CERTIFICADO_DE_CONCLUSAO_DO_ENSINO_MEDIO_FRENTE_E_VERSO";
        public const string ATO_NATURALIZACAO = "ATO_NATURALIZACAO";
        public const string CERTIDAO_DE_CASAMENTO = "CERTIDAO_DE_CASAMENTO";
        public const string CERTIDAO_DE_NASCIMENTO = "CERTIDAO_DE_NASCIMENTO";
        public const string DOCUMENTO_DE_IDENTIDADE_FRENTE_E_VERSO = "DOCUMENTO_DE_IDENTIDADE_FRENTE_E_VERSO";
        public const string TITULO_DE_ELEITOR_FRENTE_E_VERSO = "TITULO_DE_ELEITOR_FRENTE_E_VERSO";
        public const string TERMO_RESPONSABILIDADE = "TERMO_RESPONSABILIDADE";
        public const string DOCUMENTACAO_COMPROBATORIA_DIPLOMA_DIGITAL = "DOCUMENTACAO_COMPROBATORIA_DIPLOMA_DIGITAL";
    }
}
