namespace SMC.Academico.Common.Constants
{
    public static class TOKEN_TIPO_NOTIFICACAO
    {
        public const string LIBERACAO_MATRICULA = "LIBERACAO_MATRICULA";
        public const string CONFIRMACAO_MATRICULA = "CONFIRMACAO_MATRICULA";
        public const string LIBERACAO_RENOVACAO_MATRICULA = "LIBERACAO_RENOVACAO_MATRICULA";
        public const string ALTERACAO_PERIODO_VIGENCIA = "ALTERACAO_PERIODO_VIGENCIA";
        public const string ENCERRAMENTO_SOLICITACAO = "ENCERRAMENTO_SOLICITACAO";
        public const string CHANCELA_RENOVACAO_CONCLUIDA = "CHANCELA_RENOVACAO_CONCLUIDA";
        public const string CONFIRMACAO_RENOVACAO_MATRICULA = "CONFIRMACAO_RENOVACAO_MATRICULA";
        public const string CONFIRMACAO_MATRICULA_REABERTURA = "CONFIRMACAO_MATRICULA_REABERTURA";
        public const string CHANCELA_PLANO_ESTUDO_CONCLUIDA = "CHANCELA_PLANO_ESTUDO_CONCLUIDA";


        public const string PRORROGACAO_DEFERIDA = "ENCERRAMENTO_SOLICITACAO_PRORROGACAO_DEFERIDA";
        public const string PRORROGACAO_INDEFERIDA = "ENCERRAMENTO_SOLICITACAO_PRORROGACAO_INDEFERIDA";
        public const string REABERTURA_MATRICULA_DEFERIDA = "ENCERRAMENTO_SOLICITACAO_REABERTURA_MATRICULA_DEFERIDA";
        public const string REABERTURA_MATRICULA_INDEFERIDA = "ENCERRAMENTO_SOLICITACAO_REABERTURA_MATRICULA_INDEFERIDA";

        public const string TRANCAMENTO_MATRICULA_DEFERIDA = "DEFERIMENTO_PEDIDO_TRANCAMENTO_MATRICULA";

        public const string CRIACAO_SOLICITACAO_PORTAL_ALUNO = "CRIACAO_SOLICITACAO_PORTAL_ALUNO";
        public const string CRIACAO_SOLICITACAO_ATUALIZACAO_DOCUMENTACAO = "CRIACAO_SOLICITACAO_ATUALIZACAO_DOCUMENTACAO";

        public const string CHANCELA_PROGRAMA_DESTINO_SECRETARIA = "CHANCELA_PROGRAMA_DESTINO_SECRETARIA";
        public const string FINALIZACAO_SOLICITACAO_SECRETARIA = "FINALIZACAO_SOLICITACAO_SECRETARIA";
        public const string FINALIZACAO_SOLICITACAO_ORIENTADOR = "FINALIZACAO_SOLICITACAO_ORIENTADOR";
        public const string FINALIZACAO_SOLICITACAO_ENTREGA_DOCUMENTO = "FINALIZACAO_SOLICITACAO_ENTREGA_DOCUMENTO";
        public const string FINALIZACAO_SOLICITACAO_ATUALIZACAO_DOCUMENTO_CRA = "FINALIZACAO_SOLICITACAO_ATUALIZACAO_DOCUMENTO_CRA";

        public const string REABERTURA_SOLICITACAO = "REABERTURA_SOLICITACAO";

        public const string ALUNO_CANCELADO_ENCERRAMENTO_PROCESSO_RENOVACAO = "ALUNO_CANCELADO_ENCERRAMENTO_PROCESSO_RENOVACAO";

        public const string BENEFICIO_AGUARDANDO_CHANCELA = "BENEFICIO_AGUARDANDO_CHANCELA";

        public const string ALTERACAO_VIGENCIA_BENEFICIO = "ALTERACAO_VIGENCIA_BENEFICIO";

        public const string CONVITE_AVALIACAO_PROGRAMA = "CONVITE_AVALIACAO_PROGRAMA";

        public const string COMUNICADO_NOVA_FORMACAO_ESPECIFICA_PROGRAMA = "COMUNICADO_NOVA_FORMACAO_ESPECIFICA_PROGRAMA";

        public const string LIBERACAO_CADASTRO_TRABALHO_BDP = "LIBERACAO_CADASTRO_TRABALHO_BDP";
        public const string AUTORIZACAO_PUBLICACAO_BDP = "AUTORIZACAO_PUBLICACAO_BDP";
        public const string LIBERACAO_PUBLICACAO_BDP = "LIBERACAO_PUBLICACAO_BDP";
        public const string LIBERACAO_CONSULTA_BDP = "LIBERACAO_CONSULTA_BDP";

        public const string COMUNICADO_NOVA_OFERTA_CURSO_LOCALIDADE = "COMUNICADO_NOVA_OFERTA_CURSO_LOCALIDADE";

        public const string COMUNICADO_DIPLOMA_DISPONIVEL_ENTREGA = "COMUNICADO_DIPLOMA_DISPONIVEL_ENTREGA";

        public const string COMUNICADO_SOLICITACAO_SERVICO_DOCUMENTO_ACADEMICO = "COMUNICADO_SOLICITACAO_SERVICO_DOCUMENTO_ACADEMICO";

        public const string COMUNICADO_ALUNO_CONCLUSAO_DOCUMENTO_DIGITAL = "COMUNICADO_ALUNO_CONCLUSAO_DOCUMENTO_DIGITAL";

        public const string COMUNICADO_CRA_ALUNO_INDEFERIU_DADOS_DOCUMENTO = "COMUNICADO_CRA_ALUNO_INDEFERIU_DADOS_DOCUMENTO";

        public const string COMUNICADO_ALUNO_DOCUMENTO_CANCELADO = "COMUNICADO_ALUNO_DOCUMENTO_CANCELADO";

        public const string COMUNICADO_ALUNO_DOCUMENTO_DISPONIVEL = "COMUNICADO_ALUNO_DOCUMENTO_DISPONIVEL";

        public const string NOVA_ENTREGA_DOCUMENTACAO = "NOVA_ENTREGA_DOCUMENTACAO";

        public const string DOCUMENTO_INDEFERIDO_PENDENTE = "DOCUMENTO_INDEFERIDO_PENDENTE";

        public const string ALTERACAO_PLANO_DISCIPLINA_CONCLUIDA_ALUNO = "ALTERACAO_PLANO_DISCIPLINA_CONCLUIDA_ALUNO"; 

        public const string ALTERACAO_PLANO_DISCIPLINA_CONCLUIDA_PROF_SEC = "ALTERACAO_PLANO_DISCIPLINA_CONCLUIDA_PROF_SEC";

        public const string POTENCIAL_REGISTRO_TRABALHO = "POTENCIAL_REGISTRO_TRABALHO";

        public const string MUDANCA_TIPO_PUBLICACAO = "MUDANCA_TIPO_PUBLICACAO";

        public const string REABERTURA_SOLICITACAO_ATUALIZACAO_DOCUMENTO = "REABERTURA_SOLICITACAO_ATUALIZACAO_DOCUMENTO";
    }
}
