namespace SMC.Academico.Common.Areas.ALN.Constants
{
    public static class MatriculaTokens
    {
        #region Primeira etapa

        public const string INSTRUCOES_INICIAIS_MATRICULA = "INSTRUCOES_INICIAIS_MATRICULA";
        public const string SELECAO_TURMA_MATRICULA = "SELECAO_TURMA_MATRICULA";
        public const string SELECAO_ATIVIDADE_ACADEMICA_MATRICULA = "SELECAO_ATIVIDADE_ACADEMICA_MATRICULA";
        public const string SELECAO_CONDICAO_PGTO_MATRICULA = "SELECAO_CONDICAO_PGTO_MATRICULA";
        public const string ADESAO_CONTRATO_MATRICULA = "ADESAO_CONTRATO_MATRICULA";
        public const string INSTRUCOES_FINAIS_MATRICULA = "INSTRUCOES_FINAIS_MATRICULA";
        public const string INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA = "INSTRUCOES_FINAIS_SOLICITACAO_MATRICULA";
        public const string SOLICITACAO_ALTERACAO_PLANO_ESTUDOS = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO";
        public const string SOLICITACAO_ALTERACAO_PLANO_ESTUDOS_DI = "SOLICITACAO_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA";
        public const string SOLICITACAO_INCLUSAO_DISCIPLINA_ELETIVA = "SOLICITACAO_INCLUSAO_DISCIPLINA_ELETIVA";
        public const string ADESAO_CONTRATO_RENOVACAO = "ADESAO_CONTRATO_RENOVACAO";
        public const string SOLICITACAO_FORMULARIO = "SOLICITACAO_FORMULARIO";
        public const string SOLICITACAO_UPLOAD_DOCUMENTO = "SOLICITACAO_UPLOAD_DOCUMENTO";
        public const string COMPLEMENTACAO_DADOS_CADASTRAIS = "COMPLEMENTACAO_DADOS_CADASTRAIS";
        public const string MONTAGEM_PLANO_ESTUDOS = "MONTAGEM_PLANO_ESTUDOS";
        public const string SOLICITACAO_DISPENSA_DISCIPLINA = "SOLICITACAO_DISPENSA_DISCIPLINA";
        public const string ADESAO_CONTRATO_LATO_SENSU = "ADESAO_CONTRATO_LATO_SENSU";

        #region Páginas

        public const string PAGINA_INSTRUCOES_INICIAIS_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_INSTRUCOES_INICIAIS_MATRICULA_ARQUIVOS = "ARQUIVOS";
        public const string PAGINA_SELECAO_TURMA_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_SELECAO_CONDICAO_PAGAMENTO_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_ADESAO_CONTRATO_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_SELECAO_ATIVIDADE_ACADEMICA_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_EMISSAO_BOLETO_MATRICULA_INSTRUCOES_BOLETO_ZERADO = "INSTRUCOES_BOLETO_ZERADO";
        public const string PAGINA_EMISSAO_BOLETO_MATRICULA_INSTRUCOES_BOLETO_ZERADO_PAGAR = "INSTRUCOES_BOLETO_ZERADO_A_PAGAR";
        public const string PAGINA_EMISSAO_BOLETO_MATRICULA_INSTRUCOES_BOLETO_A_PAGAR = "INSTRUCOES_BOLETO_A_PAGAR";
        public const string PAGINA_INSTRUCOES_FINAIS_MATRICULA_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_COMPLEMENTACAO_DADOS_CADASTRAIS_INSTRUCOES = "INSTRUCOES";
        public const string PAGINA_MONTAGEM_PLANO_ESTUDOS_INSTRUCOES = "INSTRUCOES";

        public const string PAGINA_INSTRUCOES_REGISTRO_DOCUMENTO = "INSTRUCOES";
        public const string PAGINA_INSTRUCOES_CONFIRMAR_SELECAO_TURMAS = "INSTRUCOES";
        public const string PAGINA_INSTRUCOES_CONFIRMAR_SELECAO_ATIVIDADES_ACADEMICAS = "INSTRUCOES";
        public const string PAGINA_INSTRUCOES_EFETIVACAO_MATRICULA = "INSTRUCOES";

        #endregion Páginas

        #endregion Primeira etapa

        #region Segunda etapa

        public const string CHANCELA = "CHANCELA";
        public const string CHANCELA_PLANO_ESTUDO = "CHANCELA_PLANO_ESTUDO";
        public const string CHANCELA_RENOVACAO_MATRICULA = "CHANCELA_RENOVACAO_MATRICULA";
        public const string CHANCELA_ALTERACAO_PLANO_ESTUDO = "CHANCELA_ALTERACAO_PLANO_ESTUDO";
        public const string CHANCELA_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA = "CHANCELA_ALTERACAO_PLANO_ESTUDO_DISCIPLINA_ISOLADA";
        public const string CHANCELA_DISCIPLINA_ELETIVA_ORIGEM = "CHANCELA_DISCIPLINA_ELETIVA_ORIGEM";
        public const string EFETIVACAO_MATRICULA = "EFETIVACAO_MATRICULA";
        public const string EFETIVACAO = "EFETIVACAO";

        #endregion Segunda etapa

        #region Terceira etapa

        public const string CHANCELA_DISCIPLINA_ELETIVA_DESTINO = "CHANCELA_DISCIPLINA_ELETIVA_DESTINO";
        public const string PROCESSAMENTO_PLANO_ESTUDO = "PROCESSAMENTO_PLANO_ESTUDO";

        #endregion Terceira etapa

        #region Quarta etapa

        public const string REGISTRO_DOCUMENTO_ENTREGUE = "REGISTRO_DOCUMENTO_ENTREGUE";
        public const string CONFIRMACAO_SELECAO_TURMA = "CONFIRMACAO_SELECAO_TURMA";
        public const string CONFIRMACAO_SELECAO_ATIVIDADE_ACADEMICA = "CONFIRMACAO_SELECAO_ATIVIDADE_ACADEMICA";
        public const string CONCLUSAO_MATRICULA = "CONCLUSAO_MATRICULA";

        //public const string CONFIRMACAO_MATRICULA = "CONFIRMACAO_MATRICULA";
        //public const string REGISTRA_COMPROVANTE_PAGAMENTO = "REGISTRA_COMPROVANTE_PAGAMENTO";

        #endregion Quarta etapa

    }
}