namespace SMC.Academico.Common.Areas.PES.Constants
{
    public class TOKEN_TIPO_MENSAGEM
    {
        public const string MATERIAL_DIDATICO_INCLUSAO = "MATERIAL_DIDATICO_INCLUSAO";

        public const string MATERIAL_DIDATICO_ALTERACAO = "MATERIAL_DIDATICO_ALTERACAO";

        public const string FECHAMENTO_DIARIO = "FECHAMENTO_DIARIO";

        public const string NOTA_FINAL = "NOTA_FINAL";

        public const string FREQUENCIA_FINAL = "FREQUENCIA_FINAL";

        public const string ABERTURA_SOLICITACAO_SERVICO = "ABERTURA_SOLICITACAO_SERVICO";

        public const string ENCERRAMENTO_SOLICITACAO_SERVICO = "ENCERRAMENTO_SOLICITACAO_SERVICO";

        public const string ENCERRAMENTO_SOLICITACAO_RENOVACAO_REABERTURA = "ENCERRAMENTO_SOLICITACAO_RENOVACAO_REABERTURA";

        public const string RENOVACAO_AUTOMATICA_MOBILIDADE = "RENOVACAO_AUTOMATICA_MOBILIDADE";

        public const string RENOVACAO_AUTOMATICA_PROVAVEL_FORMANDO = "RENOVACAO_AUTOMATICA_PROVAVEL_FORMANDO";

        public const string HISTORICO_ESCOLAR_OBS_ADMISSAO = "HISTORICO_ESCOLAR_OBS_ADMISSAO";

        public const string HISTORICO_ESCOLAR_OBSERVACAO = "HISTORICO_ESCOLAR_OBSERVACAO";

        public const string REABERTURA_SOLICITACAO_SERVICO = "REABERTURA_SOLICITACAO_SERVICO";

        public const string NOTA_AVALIACAO = "NOTA_AVALIACAO";

        public const string NOTA_AVALIACAO_EXCLUIDA = "NOTA_AVALIACAO_EXCLUIDA";

        public const string REGIME_ESPECIAL_ESTUDO = "REGIME_ESPECIAL_ESTUDO";

        public const string ABONO_POR_PERIODO = "ABONO_POR_PERIODO";

        public const string SANSAO_DISCIPLINAR_SUSPENSAO = "SANSAO_DISCIPLINAR_SUSPENSAO";

        public const string DIPLOMA_NOVA_VIA = "DIPLOMA_NOVA_VIA";

        public const string DIPLOMA_CONVENIO_PEC = "DIPLOMA_CONVENIO_PEC";

        public const string DIPLOMA_PUC_UBERLANDIA = "DIPLOMA_PUC_UBERLANDIA";

        public const string DIPLOMA_BACHARELADO_LICENCIATURA = "DIPLOMA_BACHARELADO_LICENCIATURA";

        public const string HISTORICO_ESCOLAR_NOVA_VIA = "HISTORICO_ESCOLAR_NOVA_VIA";

        public const string NOME_SOCIAL_AUTORIZADO_CAD = "NOME_SOCIAL_AUTORIZADO_CAD";

        public const string DIPLOMA_HISTORICO_OBSERVACAO_LEGADO = "DIPLOMA_HISTORICO_OBSERVACAO_LEGADO";
    }
}