namespace SMC.Academico.Common.Areas.PES.Constants
{
    public class TOKEN_MOTIVO_BLOQUEIO
    {
        public const string ENTREGA_DOCUMENTACAO = "ENTREGA_DOCUMENTACAO";

        public const string PARCELA_PRE_MATRICULA_PENDENTE = "PARCELA_PRE_MATRICULA_PENDENTE";

        public const string PARCELA_MATRICULA_PENDENTE = "PARCELA_MATRICULA_PENDENTE";

        public const string FORMACAO_ESPECIFICA_PENDENTE = "FORMACAO_ESPECIFICA_PENDENTE";

        public const string ORIENTACAO_PENDENTE = "ORIENTACAO_PENDENTE";

        public const string PRAZO_CONCLUSAO_CURSO_ENCERRADO = "PRAZO_CONCLUSAO_CURSO_ENCERRADO";

        public const string PARCELA_SERVICO_ADICIONAL_PENDENTE = "PARCELA_SERVICO_ADICIONAL_PENDENTE";

        public const string IMPEDIMENTO_RENOVACAO_PRAZO_CONCLUSAO = "IMPEDIMENTO_RENOVACAO_PRAZO_CONCLUSAO";

        public const string ENTREGA_DIPLOMA_DANIFICADO = "ENTREGA_DIPLOMA_DANIFICADO";

        public const string PAGAMENTO_TAXA_SERVICO_ACADEMICO_EM_ABERTO = "PAGAMENTO_TAXA_SERVICO_ACADEMICO_EM_ABERTO";

        public const string MATERIAL_PENDENTE_BIBLIOTECA = "MATERIAL_PENDENTE_BIBLIOTECA";
    }
}