//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.ORT.Views.LancamentoNotaBancaExaminadora.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.ORT.Views.LancamentoNotaBancaExaminadora.App_LocalRe" +
                            "sources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento de Nota.
        /// </summary>
        public static string Botao_Editar_Aplicacao_Avaliacao_Banca {
            get {
                return ResourceManager.GetString("Botao_Editar_Aplicacao_Avaliacao_Banca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento de Nota.
        /// </summary>
        public static string Botao_Lancar_Nota_Banca_Examinadora {
            get {
                return ResourceManager.GetString("Botao_Lancar_Nota_Banca_Examinadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banca examinadora.
        /// </summary>
        public static string MembrosBancaExaminadora_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("MembrosBancaExaminadora_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ata de defesa não foi anexada. Deseja mesmo assim, realizar o lançamento da nota/conceito?.
        /// </summary>
        public static string MSG_Ata_Nao_Anexada_Publicacao_Biblioteca {
            get {
                return ResourceManager.GetString("MSG_Ata_Nao_Anexada_Publicacao_Biblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta nota/conceito informado aprova o aluno de acordo com o critério de aprovação configurado para o trabalho. Sendo assim, ao confirmar esta operação fará com que o aluno esteja apto a cadastrar e autorizar a publicação deste trabalho na biblioteca. Deseja continuar?.
        /// </summary>
        public static string MSG_Confirmacao_LancamentoAprovacaoNota {
            get {
                return ResourceManager.GetString("MSG_Confirmacao_LancamentoAprovacaoNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento de Nota.
        /// </summary>
        public static string Title_Lancar_Nota_Banca_Examinadora {
            get {
                return ResourceManager.GetString("Title_Lancar_Nota_Banca_Examinadora", resourceCulture);
            }
        }
    }
}
