#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
    using SMC.Academico.UI.Mvc.Areas.ALN.Lookups;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
    using SMC.Framework;
    
    #line default
    #line hidden
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/ALN/Lookups/LK_ALN_002_Termo_Intercambio/_DetailList.cshtml")]
    public partial class _Areas_ALN_Lookups_LK_ALN_002_Termo_Intercambio__DetailList_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<TermoIntercambioLookupViewModel>
    {
        public _Areas_ALN_Lookups_LK_ALN_002_Termo_Intercambio__DetailList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
 using (Smc.Div().Size(SMCSize.Grid24_24).CssClass("smc-listdetailed-item").Begin())
{
    using (Smc.Div().CssClass("smc-listdetailed-conteudo").Size(SMCSize.Grid24_24).Begin())
    {
        // Header item
        using (Smc.Div().CssClass("smc-listdetailed-header-conteudo").Size(SMCSize.Grid24_24).Begin())
        {
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
       Write(Smc.DisplayFor(m => m.Descricao).Size(SMCSize.Grid16_24));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
                                                                     
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
       Write(Smc.DisplayFor(m => m.TipoTermoIntercambio).Size(SMCSize.Grid8_24));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
                                                                               
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
       Write(Smc.DisplayFor(m => m.InstituicaoEnsinoExterna).Size(SMCSize.Grid12_24));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
                                                                                    
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
       Write(Smc.DisplayFor(m => m.DataInicio).Size(SMCSize.Grid6_24));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
                                                                     
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
       Write(Smc.DisplayFor(m => m.DataFim).Size(SMCSize.Grid6_24));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
                                                                  
        }

        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_DetailList.cshtml"
               
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
