#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    using SMC.Academico.UI.Mvc.Areas.ALN.Lookups;
    
    #line default
    #line hidden
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    
    #line 2 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    using SMC.Framework.UI.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    using SMC.Framework.UI.Mvc.Html;
    
    #line default
    #line hidden
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/ALN/Lookups/LK_ALN_002_Termo_Intercambio/_List.cshtml")]
    public partial class _Areas_ALN_Lookups_LK_ALN_002_Termo_Intercambio__List_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMC.Framework.Model.SMCPagerModel<object>>
    {
        public _Areas_ALN_Lookups_LK_ALN_002_Termo_Intercambio__List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
     if (Model.SMCCount() > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" data-type=\"smc-datagrid-container\"");

WriteLiteral(" data-default=\"true\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 10 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
        Write(Smc.List("SelectedValues", Model)
                     .AllowSelect(true)
                     .HtmlTemplate(
                    item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 14 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
                         Html.ExternalPartial(SMC.Academico.UI.Mvc.AcademicoExternalViews._TERMO_INTERCAMBIO_002_DETAIL_LIST, (item as TermoIntercambioLookupViewModel)));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n                    ");

WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 16 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
})                           )
            );

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>    \r\n");

            
            #line 19 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>");

            
            #line 22 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
      Write(Smc.GetUIResource("DataSelector_Resultado_Vazio"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 23 "..\..\Areas\ALN\Lookups\LK_ALN_002_Termo_Intercambio\_List.cshtml"
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
