//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.Academico.Common.Areas.CAM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.Academico.Common.Areas.CAM.Resources.ExceptionsResource", typeof(ExceptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Já existem convocados para a chamada {0}. Não é possível alterar o grupo de escalonamento..
        /// </summary>
        internal static string ERR_Alterar_Grupo_escalonamento_Exception {
            get {
                return ResourceManager.GetString("ERR_Alterar_Grupo_escalonamento_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. Já existe outra campanha com a mesma descrição..
        /// </summary>
        internal static string ERR_CampanhaDescricaoRepetidaException {
            get {
                return ResourceManager.GetString("ERR_CampanhaDescricaoRepetidaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu curso estará em extinção ou extinto no início do período letivo.
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoCursoExtintoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoCursoExtintoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu curso x unidade estará em extinção ou extinto no início do período letivo..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoCursoUnidadeExtintoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoCursoUnidadeExtintoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. A oferta {0} já foi associada à campanha.
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoDuplicadaExtintoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoDuplicadaExtintoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua formação específica está desativada ou não estará mais vigente na data início do período letivo..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoFormacaoEspecificaDesativadaException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoFormacaoEspecificaDesativadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua oferta de curso está desativada..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoOfertaCursoDesativadoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoOfertaCursoDesativadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua oferta de curso por localidade estará em extinção ou extinta no início do período letivo..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoOfertaCursoLocalidadeExtintoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoOfertaCursoLocalidadeExtintoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. A turma está cancelada.
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoTurmaCanceladaException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoTurmaCanceladaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. A turma {0} gera orientação. Turmas que geram orientação não podem ser ofertadas como disciplina isolada..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoTurmaGeraOrientacaoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoTurmaGeraOrientacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu turno está desativado para a oferta de curso por localidade..
        /// </summary>
        internal static string ERR_CampanhaOfertaAssociacaoTurnoDesativadoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaOfertaAssociacaoTurnoDesativadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período de inscrição das ofertas não pode ultrapassar o período da etapa de inscrição..
        /// </summary>
        internal static string ERR_CampanhaPeriodoInscricaoOfertaMaiorPeriodoInscricaoEtapaException {
            get {
                return ResourceManager.GetString("ERR_CampanhaPeriodoInscricaoOfertaMaiorPeriodoInscricaoEtapaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O processo {0} não pode ser copiado. Seu tipo de processo não está mais ativo para os níveis de ensino, o vínculo e/ou a forma de ingresso do processo..
        /// </summary>
        internal static string ERR_CampanhaTipoProcessoNaoVilculadoNivelEnsinoVinculoFormaIngressoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaTipoProcessoNaoVilculadoNivelEnsinoVinculoFormaIngressoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. Existe outra campanha para {0} no(s) ciclo(s) letivo(s) informado(s)..
        /// </summary>
        internal static string ERR_CampanhaUnidadeResponsavelCicloLetivoRepetidoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaUnidadeResponsavelCicloLetivoRepetidoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de oferta {0} não está mais ativo para {1}. As ofertas deste tipo não poderão ser copiadas..
        /// </summary>
        internal static string ERR_CampanhaUnidadeResponsavelTipoOfertaNaoVinculadoException {
            get {
                return ResourceManager.GetString("ERR_CampanhaUnidadeResponsavelTipoOfertaNaoVinculadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo letivo é inválido!.
        /// </summary>
        internal static string ERR_CicloLetivoInvalidoException {
            get {
                return ResourceManager.GetString("ERR_CicloLetivoInvalidoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua oferta de curso está desativada..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaCursoDesativadaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaCursoDesativadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu curso estará em extinção ou extinto no início do período letivo..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaCursoExtintaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaCursoExtintaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua oferta de curso por localidade estará em extinção ou extinta no início do período letivo..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaCursoLocalidadeExtintaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaCursoLocalidadeExtintaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu curso x unidade estará em extinção ou extinto no início do período letivo..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaCursoUnidadeExtintaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaCursoUnidadeExtintaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Sua formação específica está desativada ou não estará mais vigente na data início do período letivo..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaFormacaoEspecificaDesativadaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaFormacaoEspecificaDesativadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. A turma está cancelada..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaTurmaCanceladaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaTurmaCanceladaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oferta {0} não pode ser selecionada. Seu turno está desativado para a oferta de curso por localidade..
        /// </summary>
        internal static string ERR_CopiaCampanhaOfertaTurnoDesativadoParaOfertaException {
            get {
                return ResourceManager.GetString("ERR_CopiaCampanhaOfertaTurnoDesativadoParaOfertaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido alterar o tipo de abrangência, porque o tipo de evento em questão já foi parametrizado por ciclo letivo..
        /// </summary>
        internal static string ERR_ImpossivelAlterarAbrangenciaException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarAbrangenciaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido alterar o valor do campo “Somente um por parametrização”, porque o tipo de evento em questão já foi parametrizado por ciclo letivo..
        /// </summary>
        internal static string ERR_ImpossivelAlterarApenasUmaParametrizacaoException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarApenasUmaParametrizacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de parâmetro &quot;{0}&quot; não pode ser obrigatório, pois existe parametrização por ciclo letivo para o tipo de evento em questão, onde este tipo de parâmetro não foi informado..
        /// </summary>
        internal static string ERR_ImpossivelAlterarObrigatorioDeNaoParaSimException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarObrigatorioDeNaoParaSimException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido trocar o tipo de agenda &quot;{0}&quot;, porque já existe evento letivo cadastrado para o tipo de evento em questão..
        /// </summary>
        internal static string ERR_ImpossivelAlterarTipoAgendaException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarTipoAgendaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido trocar o tipo de evento &quot;{0}&quot;, porque ele já foi parametrizado por ciclo letivo..
        /// </summary>
        internal static string ERR_ImpossivelAlterarTipoEventoException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarTipoEventoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido alterar o tipo de parâmetro &quot;{0}&quot;, porque ele já foi parametrizado por ciclo letivo..
        /// </summary>
        internal static string ERR_ImpossivelAlterarTipoParametroException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelAlterarTipoParametroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido excluir o tipo de parâmetro &quot;{0}&quot;, porque ele já foi parametrizado por ciclo letivo..
        /// </summary>
        internal static string ERR_ImpossivelExcluirTipoParametroException {
            get {
                return ResourceManager.GetString("ERR_ImpossivelExcluirTipoParametroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem convocados nesta chamada para liberação para matrícula..
        /// </summary>
        internal static string ERR_NaoExistemConvocadosParaLiberacaoException {
            get {
                return ResourceManager.GetString("ERR_NaoExistemConvocadosParaLiberacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório selecionar ao menos um ciclo letivo..
        /// </summary>
        internal static string ERR_ObrigatoriedadeCopiaCiclo {
            get {
                return ResourceManager.GetString("ERR_ObrigatoriedadeCopiaCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório selecionar ciclos letivos do mesmo ano para a cópia..
        /// </summary>
        internal static string ERR_ObrigatoriedadeSelecaoMesmoAno {
            get {
                return ResourceManager.GetString("ERR_ObrigatoriedadeSelecaoMesmoAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existe oferta cuja quantidade de vagas é maior que as vagas configuradas no processo seletivo &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_OfertaVagaMaiorConvocacaoProcessoSeletivoException {
            get {
                return ResourceManager.GetString("ERR_OfertaVagaMaiorConvocacaoProcessoSeletivoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existe oferta cuja quantidade de vagas é maior que as vagas configuradas na oferta da campanha..
        /// </summary>
        internal static string ERR_OfertaVagaMaiorProcessoSeletivoException {
            get {
                return ResourceManager.GetString("ERR_OfertaVagaMaiorProcessoSeletivoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existe oferta cuja quantidade de vagas é menor que as vagas configuradas no(s) processo(s) seletivo(s)..
        /// </summary>
        internal static string ERR_OfertaVagaMenorProcessoSeletivoException {
            get {
                return ResourceManager.GetString("ERR_OfertaVagaMenorProcessoSeletivoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido aumentar a quantidade de vagas das ofertas listadas abaixo, pois suas turmas não possuem vagas suficientes:
        ///{0}.
        /// </summary>
        internal static string ERR_OfertaVagaTurmaInsuficienteException {
            get {
                return ResourceManager.GetString("ERR_OfertaVagaTurmaInsuficienteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Não é permitido diminuir as vagas das ofertas listadas abaixo, pois já estão ocupadas:
        ///{0}.
        /// </summary>
        internal static string ERR_OfertaVagaTurmaOcupadaInsuficienteException {
            get {
                return ResourceManager.GetString("ERR_OfertaVagaTurmaOcupadaInsuficienteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem ingressantes que não possuem as orientações para liberação da matricula..
        /// </summary>
        internal static string ERR_OrientacaoConvocadosException {
            get {
                return ResourceManager.GetString("ERR_OrientacaoConvocadosException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(s) parâmetro(s) &quot;{0}&quot; são obrigatórios para verificação do período do evento letivo informado..
        /// </summary>
        internal static string ERR_PeriodoEventoLetivoNullArgumentException {
            get {
                return ResourceManager.GetString("ERR_PeriodoEventoLetivoNullArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum evento letivo com os parâmetros {0}..
        /// </summary>
        internal static string ERR_PeriodoEventoLetivoVazioException {
            get {
                return ResourceManager.GetString("ERR_PeriodoEventoLetivoVazioException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. O processo do GPI associado ao processo seletivo desta oferta não possui etapa de inscrição cadastrada..
        /// </summary>
        internal static string ERR_ProcessoGPISemEtapaInscricaoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoGPISemEtapaInscricaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. O processo de matrícula {0} não foi configurado para os níveis de ensino ou cursos de oferta por localidade e turno das ofertas associadas a este processo seletivo e para o vínculo informado..
        /// </summary>
        internal static string ERR_ProcessoMatriculaNaoConfiguradoCursoNivelEnsinoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoMatriculaNaoConfiguradoCursoNivelEnsinoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. O processo de matrícula {0} não foi configurado para os níveis de ensino ou cursos de oferta localidade e turno das ofertas associadas a este processo seletivo e para o(s) vínculo(s) da(s) forma(s) de ingresso do tipo de processo seletivo informado..
        /// </summary>
        internal static string ERR_ProcessoMatriculaNaoConfiguradoCursoNivelSemVinculoEnsinoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoMatriculaNaoConfiguradoCursoNivelSemVinculoEnsinoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação  não permitida. Somente um processo de matrícula pode ser associado por ciclo letivo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoCicloLetivoDuplicadoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoCicloLetivoDuplicadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existem ingressantes para o processo de matrícula {0} no ciclo letivo {1}..
        /// </summary>
        internal static string ERR_ProcessoSeletivoComIngressanteException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoComIngressanteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existem ofertas do nível de ensino {0} associadas a este processo seletivo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoComNivelEnsinoAssociadoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoComNivelEnsinoAssociadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Não é permitido trocar a configuração de reserva de vagas, quando já existem ofertas associadas ao processo seletivo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoComOfertasException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoComOfertasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Existem ofertas associadas a este processo seletivo cujo tipo de oferta não é permitido para o tipo de processo seletivo informado..
        /// </summary>
        internal static string ERR_ProcessoSeletivoComTipoOfertasDiferentesException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoComTipoOfertasDiferentesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. O processo de matrícula {0} não foi configurado para o(s) nível(is) de ensino e o vínculo informados..
        /// </summary>
        internal static string ERR_ProcessoSeletivoNaoConfiguradoNivelEnsinoComVinculoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoNaoConfiguradoNivelEnsinoComVinculoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. A oferta {0} já foi associada à convocação..
        /// </summary>
        internal static string ERR_ProcessoSeletivoOfertaConvocacaoDuplicadaException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoOfertaConvocacaoDuplicadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. A oferta {0} já foi associada ao processo seletivo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoOfertaDuplicadaException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoOfertaDuplicadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. Existem ofertas cujo nível de ensino ou a oferta de curso por localidade e turno não estão configuradas para o(s) processo(s) de matrícula e o(s) vínculo(s) da(s) forma(s) de ingresso do tipo de processo seletivo do processo seletivo em questão..
        /// </summary>
        internal static string ERR_ProcessoSeletivoOfertaNivelEnsinoOfertaCursoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoOfertaNivelEnsinoOfertaCursoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação não permitida. Existem ofertas cujo nível de ensino ou a oferta de curso por localidade e turno não estão configurados para o processo de matrícula do processo seletivo e do ciclo letivo desta convocação e para vínculo do processo seletivo em questão..
        /// </summary>
        internal static string ERR_ProcessoSeletivoOfertaVinculoConvocacaoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoOfertaVinculoConvocacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Existe ingressante associado à oferta {0}, para o processo seletivo {1}..
        /// </summary>
        internal static string ERR_ProcessoSeletivoOfertaVinculoIngressanteExcluirException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoOfertaVinculoIngressanteExcluirException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O template do processo GPI {0} está desativado para o tipo de processo deste processo. Não é possível copiar as etapas..
        /// </summary>
        internal static string ERR_ProcessoSeletivoTemplateProcessoDesativadoTipoProcessoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoTemplateProcessoDesativadoTipoProcessoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de hierarquia do processo GPI {0} está desativado para o tipo de processo e a unidade responsável deste processo. Não é possível copiar a(as) oferta(s) para este processo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoTipoHierarquiaProcessoGpiDesativadoTipoProcessoUnidadeResponsavelException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoTipoHierarquiaProcessoGpiDesativadoTipoProcessoUnidadeRespons" +
                        "avelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de processo do processo GPI {0} está desativado para a unidade responsável deste processo. Não é possível copiar as ofertas e as etapas do processo..
        /// </summary>
        internal static string ERR_ProcessoSeletivoTipoProcessoGpiDesativadoUnidadeResponsavelException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoTipoProcessoGpiDesativadoUnidadeResponsavelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O processo {0} não pode ser copiado. O tipo de processo do GPI não pode mais ser vinculado ao tipo de processo deste processo seletivo do SGA..
        /// </summary>
        internal static string ERR_ProcessoSeletivoTipoProcessoGpiNaoVinculadoTipoProcessoException {
            get {
                return ResourceManager.GetString("ERR_ProcessoSeletivoTipoProcessoGpiNaoVinculadoTipoProcessoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este regime letivo já está sendo utilizado. Não é possível alterar a quantidade de itens ano..
        /// </summary>
        internal static string ERR_QuantidadeItensAnoUtilizado {
            get {
                return ResourceManager.GetString("ERR_QuantidadeItensAnoUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Não é possível reduzir {0} vagas da oferta {1} na convocação {2}, pois não existem vagas suficientes..
        /// </summary>
        internal static string ERR_ReducaoVagaOfertaConvocacaoInvalidaException {
            get {
                return ResourceManager.GetString("ERR_ReducaoVagaOfertaConvocacaoInvalidaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Não é possível reduzir {0} vagas da oferta {1} no processo seletivo {2}, pois não existem vagas suficientes..
        /// </summary>
        internal static string ERR_ReducaoVagaOfertaProcessoSeletivoInvalidaException {
            get {
                return ResourceManager.GetString("ERR_ReducaoVagaOfertaProcessoSeletivoInvalidaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração não permitida. Não é possível replicar vagas para as ofertas da convocação, sem selecionar seu respectivo processo seletivo..
        /// </summary>
        internal static string ERR_ReplicarOfertaVagaProcessoSeletivoException {
            get {
                return ResourceManager.GetString("ERR_ReplicarOfertaVagaProcessoSeletivoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de oferta já está sendo utilizado por uma oferta de uma campanha. Não é possível alterar o indicador &quot;Exige curso oferta localidade turno&quot;..
        /// </summary>
        internal static string ERR_TipoOfertaExigeCursoOfertaLocalidadeTurnoException {
            get {
                return ResourceManager.GetString("ERR_TipoOfertaExigeCursoOfertaLocalidadeTurnoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de oferta já está sendo utilizado por uma oferta de uma campanha. Não é possível alterar o tipo de formação específica..
        /// </summary>
        internal static string ERR_TipoOfertaTipoFormacaoEspecificaException {
            get {
                return ResourceManager.GetString("ERR_TipoOfertaTipoFormacaoEspecificaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de oferta já está sendo utilizado por um processo do GPI. Não é possível alterar o tipo de item de hierarquia de oferta..
        /// </summary>
        internal static string ERR_TipoOfertaTipoItemHierarquiaOfertaGpiException {
            get {
                return ResourceManager.GetString("ERR_TipoOfertaTipoItemHierarquiaOfertaGpiException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Entidade já é responsável por campanha..
        /// </summary>
        internal static string FK_campanha_01 {
            get {
                return ResourceManager.GetString("FK_campanha_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Campanha já possui ciclo letivo associado..
        /// </summary>
        internal static string FK_campanha_ciclo_letivo_01 {
            get {
                return ResourceManager.GetString("FK_campanha_ciclo_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Ciclo letivo já está associado a campanha..
        /// </summary>
        internal static string FK_campanha_ciclo_letivo_02 {
            get {
                return ResourceManager.GetString("FK_campanha_ciclo_letivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Campanha já possui ofertas cadastradas..
        /// </summary>
        internal static string FK_campanha_oferta_01 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de oferta já possui cadastro de ofertas em campanha..
        /// </summary>
        internal static string FK_campanha_oferta_02 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Oferta já possui itens..
        /// </summary>
        internal static string FK_campanha_oferta_item_01 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_item_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Curso já possui associação com oferta de campanha..
        /// </summary>
        internal static string FK_campanha_oferta_item_02 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_item_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Turma já possui associação com oferta de campanha..
        /// </summary>
        internal static string FK_campanha_oferta_item_03 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_item_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Professor/Pesquisador já possui associaçao com oferta de campanha..
        /// </summary>
        internal static string FK_campanha_oferta_item_04 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_item_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Formação específica já possui associação com oferta de campanha..
        /// </summary>
        internal static string FK_campanha_oferta_item_05 {
            get {
                return ResourceManager.GetString("FK_campanha_oferta_item_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Instituição de ensino já possui ciclo letivo cadastrado..
        /// </summary>
        internal static string FK_ciclo_letivo_01 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão  não permitida. Regime Letivo já possui ciclo letivo cadastrado..
        /// </summary>
        internal static string FK_ciclo_letivo_02 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Ciclo letivo já possui níveis de ensino associados..
        /// </summary>
        internal static string FK_ciclo_letivo_nivel_ensino_01 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_nivel_ensino_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino já está associado a um ciclo letivo..
        /// </summary>
        internal static string FK_ciclo_letivo_nivel_ensino_02 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_nivel_ensino_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Ciclo letivo já possui tipo de evento configurado..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_01 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de evento já está configurado em ciclo letivo..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_02 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de evento já possui nível de ensino associado..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_nivel_ensino_01 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_nivel_ensino_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino já está associado a configuração de tipo de evento por ciclo letivo..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_nivel_ensino_02 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_nivel_ensino_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de evento já possui parâmetros associados..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_parametro_01 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_parametro_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Parâmetro já está configurado no tipo de evento de ciclo letivo..
        /// </summary>
        internal static string FK_ciclo_letivo_tipo_evento_parametro_02 {
            get {
                return ResourceManager.GetString("FK_ciclo_letivo_tipo_evento_parametro_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Campanha já possui convocações associadas..
        /// </summary>
        internal static string FK_convocacao_02 {
            get {
                return ResourceManager.GetString("FK_convocacao_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. A Convocação está associada a uma ou mais Ofertas..
        /// </summary>
        internal static string FK_convocacao_oferta_01 {
            get {
                return ResourceManager.GetString("FK_convocacao_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. A Convocação está associada a uma ou mais Chamadas..
        /// </summary>
        internal static string FK_convocado_01 {
            get {
                return ResourceManager.GetString("FK_convocado_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de evento já possui Evento letivo cadastrado..
        /// </summary>
        internal static string FK_evento_letivo_01 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Evento letivo possui evento AGD cadastrado..
        /// </summary>
        internal static string FK_evento_letivo_agd_01 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_agd_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Evento letivo possui nível de ensino configurado..
        /// </summary>
        internal static string FK_evento_letivo_nivel_ensino_01 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_nivel_ensino_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino está associado a uma evento letivo..
        /// </summary>
        internal static string FK_evento_letivo_nivel_ensino_02 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_nivel_ensino_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Evento letivo possui parâmetros configurados..
        /// </summary>
        internal static string FK_evento_letivo_parametro_entidade_01 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_parametro_entidade_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Entidade possui evento letivo parametrizado..
        /// </summary>
        internal static string FK_evento_letivo_parametro_entidade_02 {
            get {
                return ResourceManager.GetString("FK_evento_letivo_parametro_entidade_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Regime Letivo já está configurado para uso em um nível de ensino x instituição de ensino..
        /// </summary>
        internal static string FK_instituicao_nivel_regime_letivo_01 {
            get {
                return ResourceManager.GetString("FK_instituicao_nivel_regime_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino já possui regime letivo configurado..
        /// </summary>
        internal static string FK_instituicao_nivel_regime_letivo_02 {
            get {
                return ResourceManager.GetString("FK_instituicao_nivel_regime_letivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino já possui tipo de processo seletivo configurado..
        /// </summary>
        internal static string FK_instituicao_nivel_tipo_processo_seletivo_01 {
            get {
                return ResourceManager.GetString("FK_instituicao_nivel_tipo_processo_seletivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de processo seletivo já está configurado para uso em um nível de ensino x instituição de ensino..
        /// </summary>
        internal static string FK_instituicao_nivel_tipo_processo_seletivo_02 {
            get {
                return ResourceManager.GetString("FK_instituicao_nivel_tipo_processo_seletivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Instituição de esnino já possui tipo de evento configurado..
        /// </summary>
        internal static string FK_instituicao_tipo_evento_01 {
            get {
                return ResourceManager.GetString("FK_instituicao_tipo_evento_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de agenda já possui tipo de evento configurado..
        /// </summary>
        internal static string FK_instituicao_tipo_evento_02 {
            get {
                return ResourceManager.GetString("FK_instituicao_tipo_evento_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Configuração de tipo de evento já possui parâmetros configurados..
        /// </summary>
        internal static string FK_instituicao_tipo_evento_parametro_01 {
            get {
                return ResourceManager.GetString("FK_instituicao_tipo_evento_parametro_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Campanha já possui processos seletivos cadastrados..
        /// </summary>
        internal static string FK_processo_seletivo_01 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe processos seletivos cadastrados com este tipo de processo seletivo..
        /// </summary>
        internal static string FK_processo_seletivo_02 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe processo seletivo cadastrado com esta forma de ingresso..
        /// </summary>
        internal static string FK_processo_seletivo_03 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe processo seletivo cadastrado com esse tipo de vínculo de aluno..
        /// </summary>
        internal static string FK_processo_seletivo_04 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Processo seletivo já possui nível de ensino associado..
        /// </summary>
        internal static string FK_processo_seletivo_nivel_ensino_01 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_nivel_ensino_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Nível de ensino já está configurado em processo seletivo..
        /// </summary>
        internal static string FK_processo_seletivo_nivel_ensino_02 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_nivel_ensino_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Processo seletivo já possui ofertas cadastradas..
        /// </summary>
        internal static string FK_processo_seletivo_oferta_01 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Oferta da campanha já está associado a processo seletivo..
        /// </summary>
        internal static string FK_processo_seletivo_oferta_02 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_oferta_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe processo de matrícula configurado para este processo seletivo..
        /// </summary>
        internal static string FK_processo_seletivo_processo_matricula_01 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_processo_matricula_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe processo de matrícula configurado para este ciclo letivo da campanha..
        /// </summary>
        internal static string FK_processo_seletivo_processo_matricula_02 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_processo_matricula_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Processo de matrícula já associado a processo seletivo..
        /// </summary>
        internal static string FK_processo_seletivo_processo_matricula_03 {
            get {
                return ResourceManager.GetString("FK_processo_seletivo_processo_matricula_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de formação específica já está configurado em tipo de oferta..
        /// </summary>
        internal static string FK_tipo_oferta_01 {
            get {
                return ResourceManager.GetString("FK_tipo_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Entidade está associada a tipo de oferta..
        /// </summary>
        internal static string FK_tipo_oferta_unidade_responsavel_01 {
            get {
                return ResourceManager.GetString("FK_tipo_oferta_unidade_responsavel_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de oferta possui entidades responsáveis configuradas..
        /// </summary>
        internal static string FK_tipo_oferta_unidade_responsavel_02 {
            get {
                return ResourceManager.GetString("FK_tipo_oferta_unidade_responsavel_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de processo seletivo já possui tipo de processo GPI configurado..
        /// </summary>
        internal static string FK_tipo_processo_seletivo_gpi_01 {
            get {
                return ResourceManager.GetString("FK_tipo_processo_seletivo_gpi_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Tipo de processo seletivo já possui tipo de oferta configurada..
        /// </summary>
        internal static string FK_tipo_processo_seletivo_tipo_oferta_01 {
            get {
                return ResourceManager.GetString("FK_tipo_processo_seletivo_tipo_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida. Já existe configuração de tipo de processo seletivo utilizando este tipo de oferta..
        /// </summary>
        internal static string FK_tipo_processo_seletivo_tipo_oferta_02 {
            get {
                return ResourceManager.GetString("FK_tipo_processo_seletivo_tipo_oferta_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe campanha com esta descrição para esta unidade responsável..
        /// </summary>
        internal static string UN_campanha_01 {
            get {
                return ResourceManager.GetString("UN_campanha_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo letivo já está associado a esta campanha..
        /// </summary>
        internal static string UN_campanha_ciclo_letivo_01 {
            get {
                return ResourceManager.GetString("UN_campanha_ciclo_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe oferta com esta descrição nesta campanha..
        /// </summary>
        internal static string UN_campanha_oferta_01 {
            get {
                return ResourceManager.GetString("UN_campanha_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um ciclo letivo cadastrado para a instituição de ensino com o mesmo regime letivo, ano ciclo e nº ciclo..
        /// </summary>
        internal static string UN_ciclo_letivo_01 {
            get {
                return ResourceManager.GetString("UN_ciclo_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe configuração deste parâmetro para este ciclo letivo e tipo de evento..
        /// </summary>
        internal static string UN_ciclo_letivo_tipo_evento_parametro_01 {
            get {
                return ResourceManager.GetString("UN_ciclo_letivo_tipo_evento_parametro_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento AGD já está associado a este evento letivo..
        /// </summary>
        internal static string UN_evento_letivo_agd_01 {
            get {
                return ResourceManager.GetString("UN_evento_letivo_agd_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro já configurado para este evento letivo e entidade..
        /// </summary>
        internal static string UN_evento_letivo_parametro_entidade_01 {
            get {
                return ResourceManager.GetString("UN_evento_letivo_parametro_entidade_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regime letivo já está associado à este nível de ensino x instituição de ensino..
        /// </summary>
        internal static string UN_instituicao_nivel_regime_letivo_01 {
            get {
                return ResourceManager.GetString("UN_instituicao_nivel_regime_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo seletivo já está associado à este nível de ensino x instituição de ensino..
        /// </summary>
        internal static string UN_instituicao_nivel_tipo_processo_seletivo_01 {
            get {
                return ResourceManager.GetString("UN_instituicao_nivel_tipo_processo_seletivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evento já está configurado para esta instituição e tipo de agenda..
        /// </summary>
        internal static string UN_instituicao_tipo_evento_01 {
            get {
                return ResourceManager.GetString("UN_instituicao_tipo_evento_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este parâmetro já está configurado para esse tipo de evento..
        /// </summary>
        internal static string UN_instituicao_tipo_evento_parametro_01 {
            get {
                return ResourceManager.GetString("UN_instituicao_tipo_evento_parametro_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe processo seletivo com esta descrição nesta campanha..
        /// </summary>
        internal static string UN_processo_seletivo_01 {
            get {
                return ResourceManager.GetString("UN_processo_seletivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de ensino já está associado ao processo seletivo..
        /// </summary>
        internal static string UN_processo_seletivo_nivel_ensino_01 {
            get {
                return ResourceManager.GetString("UN_processo_seletivo_nivel_ensino_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta já está associada ao processo seletivo..
        /// </summary>
        internal static string UN_processo_seletivo_oferta_01 {
            get {
                return ResourceManager.GetString("UN_processo_seletivo_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe configuração de processo de matrícula para este processo seletivo x ciclo letivo x campanha..
        /// </summary>
        internal static string UN_processo_seletivo_processo_matricula_01 {
            get {
                return ResourceManager.GetString("UN_processo_seletivo_processo_matricula_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe regime letivo cadastrado com esta descrição..
        /// </summary>
        internal static string UN_regime_letivo_01 {
            get {
                return ResourceManager.GetString("UN_regime_letivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe tipo de oferta com esta descrição..
        /// </summary>
        internal static string UN_tipo_oferta_01 {
            get {
                return ResourceManager.GetString("UN_tipo_oferta_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe tipo de oferta com este token..
        /// </summary>
        internal static string UN_tipo_oferta_02 {
            get {
                return ResourceManager.GetString("UN_tipo_oferta_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe tipo de oferta cadastrado com essa associação ao tipo de hierarquia de oferta do GPI..
        /// </summary>
        internal static string UN_tipo_oferta_03 {
            get {
                return ResourceManager.GetString("UN_tipo_oferta_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de oferta já está associado a entidade..
        /// </summary>
        internal static string UN_tipo_oferta_unidade_responsavel_01 {
            get {
                return ResourceManager.GetString("UN_tipo_oferta_unidade_responsavel_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe tipo de processo seletivo com esta descrição nesta instituição de ensino..
        /// </summary>
        internal static string UN_tipo_processo_seletivo_01 {
            get {
                return ResourceManager.GetString("UN_tipo_processo_seletivo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe tipo de processo seletivo com este token nesta instituição de ensino..
        /// </summary>
        internal static string UN_tipo_processo_seletivo_02 {
            get {
                return ResourceManager.GetString("UN_tipo_processo_seletivo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo GPI já está associado a este tipo de processo seletivo..
        /// </summary>
        internal static string UN_tipo_processo_seletivo_gpi_01 {
            get {
                return ResourceManager.GetString("UN_tipo_processo_seletivo_gpi_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de oferta já está associado a este tipo de processo seletivo..
        /// </summary>
        internal static string UN_tipo_processo_seletivo_tipo_oferta_01 {
            get {
                return ResourceManager.GetString("UN_tipo_processo_seletivo_tipo_oferta_01", resourceCulture);
            }
        }
    }
}
