//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CNC.Views.DocumentoConclusaoApostilamento.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CNC.Views.DocumentoConclusaoApostilamento.App_LocalR" +
                            "esources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string botao_edit_documento_conclusao_apostilamento_tooltip {
            get {
                return ResourceManager.GetString("botao_edit_documento_conclusao_apostilamento_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string botao_excluir_documento_conclusao_apostilamento_tooltip {
            get {
                return ResourceManager.GetString("botao_excluir_documento_conclusao_apostilamento_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Documento Conclusão Apostilamento.
        /// </summary>
        public static string Botao_Incluir_Novo_Documento_Conclusao_Apostilamento {
            get {
                return ResourceManager.GetString("Botao_Incluir_Novo_Documento_Conclusao_Apostilamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar dados do aluno.
        /// </summary>
        public static string Botao_Manter_Aluno {
            get {
                return ResourceManager.GetString("Botao_Manter_Aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Documento Conclusão Apostilamento.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do documento conclusão apostilamento &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Documento_Conclusao_Apostilamento_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Documento_Conclusao_Apostilamento_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Documento Conclusão Apostilamento.
        /// </summary>
        public static string Exclusao_Documento_Conclusao_Apostilamento_Title {
            get {
                return ResourceManager.GetString("Exclusao_Documento_Conclusao_Apostilamento_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Conclusão Apostilamento.
        /// </summary>
        public static string gridDocumentoConclusaoApostilamento_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridDocumentoConclusaoApostilamento_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Documento Conclusão Apostilamento.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Documento Conclusão Apostilamento.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A situação atual do documento não permite alterar os dados
        ///do apostilamento..
        /// </summary>
        public static string Mensagem_Informativa {
            get {
                return ResourceManager.GetString("Mensagem_Informativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Conclusão Apostilamento salvo com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Documento_Conclusao_Apostilamento {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Documento_Conclusao_Apostilamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Conclusão Apostilamento excluído com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Exclusao_Documento_Conclusao_Apostilamento {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Exclusao_Documento_Conclusao_Apostilamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da formação específica associada ao documento de
        ///conclusão, não permite que novas formações sejam associadas..
        /// </summary>
        public static string Mensagem_TipoFormacaoEspecifica {
            get {
                return ResourceManager.GetString("Mensagem_TipoFormacaoEspecifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualize os dados pessoais do aluno de acordo com os dados
        ///que acionaram a necessidade de apostilamento do documento..
        /// </summary>
        public static string Mensagem_TokenDadosPessoais {
            get {
                return ResourceManager.GetString("Mensagem_TokenDadosPessoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao confirmar o apostilamento de nova formação específica. A
        ///formação selecionada será associada no documento de conclusão..
        /// </summary>
        public static string Mensagem_TokenFormacao {
            get {
                return ResourceManager.GetString("Mensagem_TokenFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção indisponível. A situação atual do documento não permite o cadastro de apostilamento..
        /// </summary>
        public static string MensagemDesabilitaBotaoNovo {
            get {
                return ResourceManager.GetString("MensagemDesabilitaBotaoNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho máximo de arquivo é 25MB..
        /// </summary>
        public static string Upload_Val_Arquivo_Grande_Mensagem {
            get {
                return ResourceManager.GetString("Upload_Val_Arquivo_Grande_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo muito grande.
        /// </summary>
        public static string Upload_Val_Arquivo_Grande_Titulo {
            get {
                return ResourceManager.GetString("Upload_Val_Arquivo_Grande_Titulo", resourceCulture);
            }
        }
    }
}
