//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.CUR.Views.Curriculo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.CUR.Views.Curriculo.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Currículo.
        /// </summary>
        public static string Aba_Title_0 {
            get {
                return ResourceManager.GetString("Aba_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de grupo curricular.
        /// </summary>
        public static string Botao_AssociacaoGrupoCurricular {
            get {
                return ResourceManager.GetString("Botao_AssociacaoGrupoCurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de grupo curricular.
        /// </summary>
        public static string Botao_CadastoGrupoCurricular {
            get {
                return ResourceManager.GetString("Botao_CadastoGrupoCurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de grupo curricular.
        /// </summary>
        public static string Botao_CadastoGrupoCurricular_Tooltip {
            get {
                return ResourceManager.GetString("Botao_CadastoGrupoCurricular_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de matriz curricular.
        /// </summary>
        public static string Botao_CadastroMatrizCurricular {
            get {
                return ResourceManager.GetString("Botao_CadastroMatrizCurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo currículo.
        /// </summary>
        public static string Botao_Novo {
            get {
                return ResourceManager.GetString("Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo currículo.
        /// </summary>
        public static string Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de curso.
        /// </summary>
        public static string CurriculoCursoOferta_Lista_Titulo {
            get {
                return ResourceManager.GetString("CurriculoCursoOferta_Lista_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de curso.
        /// </summary>
        public static string CursoOfertaSemCredito_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("CursoOfertaSemCredito_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de curso.
        /// </summary>
        public static string CursosOferta_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("CursosOferta_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de curso.
        /// </summary>
        public static string CursosOferta_Modal_Editar_Titulo {
            get {
                return ResourceManager.GetString("CursosOferta_Modal_Editar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Currículo.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Currículo.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Currículo.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currículo.
        /// </summary>
        public static string Label_Curriculo {
            get {
                return ResourceManager.GetString("Label_Curriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do currículo &quot;{0}&quot;?.
        /// </summary>
        public static string Listar_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("Listar_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Currículo.
        /// </summary>
        public static string Listar_Excluir_Titulo {
            get {
                return ResourceManager.GetString("Listar_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totais de créditos serão exibidos dependendo do parâmetro por instituição/nível.
        /// </summary>
        public static string Mensagem_Oferta_Curso {
            get {
                return ResourceManager.GetString("Mensagem_Oferta_Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas de Curso.
        /// </summary>
        public static string Modal_Editar_Titulo {
            get {
                return ResourceManager.GetString("Modal_Editar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem ofertas cadastradas para o curso selecionado, favor realizar o cadastro antes de prosseguir..
        /// </summary>
        public static string MSG_CurriculoCursoSemOferta {
            get {
                return ResourceManager.GetString("MSG_CurriculoCursoSemOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string Wizard_Title_0 {
            get {
                return ResourceManager.GetString("Wizard_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Currículo.
        /// </summary>
        public static string Wizard_Title_1 {
            get {
                return ResourceManager.GetString("Wizard_Title_1", resourceCulture);
            }
        }
    }
}
