#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CNC/Views/IntegralizacaoCurricular/_DivisaoIntegralizacaoCurricular.cshtm" +
        "l")]
    public partial class _Areas_CNC_Views_IntegralizacaoCurricular__DivisaoIntegralizacaoCurricular_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMC.Academico.UI.Mvc.Areas.CNC.Models.IntegralizacaoMatrizDivisaoViewModel>
    {
        public _Areas_CNC_Views_IntegralizacaoCurricular__DivisaoIntegralizacaoCurricular_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\CNC\Views\IntegralizacaoCurricular\_DivisaoIntegralizacaoCurricular.cshtml"
  
    if (Model.Grupos.SMCCount() > 0)
    {
        using (Smc.Accordion("DivisaoComGrupos").AllowMultipleOpen(true).CssClass("smc-sga-accordion-secundario").Size(SMCSize.Grid24_24).Begin())
        {
            foreach (var item in Model.Grupos)
            {
                var headerCompleto = "<div class=\"smc-sga-accordion-header-display\"><label class='titlePrincipal'>Grupo:&nbsp</label><p>" + item.DescricaoGrupo + "</p></div>" +
                                     "<div class=\"smc-sga-accordion-header-display\"><label class='titleSub'>Configuração:&nbsp</label><p>" + item.ConfiguracaoGrupo + "</p></div>" +
                                     "<div class=\"smc-sga-accordion-header-display\"><label class='titleSub'>Concluído:&nbsp</label><p>" + item.PercentualConclusaoGrupoFormatado + "</p></div>";
                using (Smc.AccordionSection("Grupo" + Guid.NewGuid().ToString()).Title(f => headerCompleto).IsOpen(false).Begin())
                {
                    var viewGrupo = Smc.GetExternalView(SMC.Academico.UI.Mvc.AcademicoExternalViews.INTEGRALIZACAO_CURRICULAR_GRUPO);
                    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CNC\Views\IntegralizacaoCurricular\_DivisaoIntegralizacaoCurricular.cshtml"
               Write(Html.Partial(viewGrupo, item));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CNC\Views\IntegralizacaoCurricular\_DivisaoIntegralizacaoCurricular.cshtml"
                                                  ;
                }
            }
        }
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
