//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.PES.Views.FormacaoAcademica.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.PES.Views.FormacaoAcademica.App_LocalResources.Metad" +
                            "ataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano início.
        /// </summary>
        internal static string AnoInicio {
            get {
                return ResourceManager.GetString("AnoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano obtenção título.
        /// </summary>
        internal static string AnoObtencaoTitulo {
            get {
                return ResourceManager.GetString("AnoObtencaoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf ou passaporte.
        /// </summary>
        internal static string CpfOuPassaporte {
            get {
                return ResourceManager.GetString("CpfOuPassaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulação.
        /// </summary>
        internal static string DescricaoTitulacao {
            get {
                return ResourceManager.GetString("DescricaoTitulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Formação Acadêmica.
        /// </summary>
        internal static string FormacaoAcademicaDynamicModel {
            get {
                return ResourceManager.GetString("FormacaoAcademicaDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulação.
        /// </summary>
        internal static string FormacaoAcademicaDynamicModel_SeqTitulacao {
            get {
                return ResourceManager.GetString("FormacaoAcademicaDynamicModel_SeqTitulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de classificação.
        /// </summary>
        internal static string SeqClassificacao {
            get {
                return ResourceManager.GetString("SeqClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição.
        /// </summary>
        internal static string SeqInstituicaoExterna {
            get {
                return ResourceManager.GetString("SeqInstituicaoExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento apresentado.
        /// </summary>
        internal static string SeqsDocumentosApresentados {
            get {
                return ResourceManager.GetString("SeqsDocumentosApresentados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulação.
        /// </summary>
        internal static string SeqTitulacao {
            get {
                return ResourceManager.GetString("SeqTitulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulação máxima.
        /// </summary>
        internal static string TitulacaoMaxima {
            get {
                return ResourceManager.GetString("TitulacaoMaxima", resourceCulture);
            }
        }
    }
}
