#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SMC.Framework;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Seguranca.UI.Mvc.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CUR/Lookups/LK_CUR_008_Grupo_Componente_Curricular/Views/_ValoresSelecion" +
        "adosLookup.cshtml")]
    public partial class _Areas_CUR_Lookups_LK_CUR_008_Grupo_Componente_Curricular_Views__ValoresSelecionadosLookup_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<SMC.Academico.UI.Mvc.Areas.CUR.Lookups.GrupoCurricularComponenteLookupViewModel>
    {
        public _Areas_CUR_Lookups_LK_CUR_008_Grupo_Componente_Curricular_Views__ValoresSelecionadosLookup_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Seq\"");

WriteAttribute("value", Tuple.Create(" value=\"", 151), Tuple.Create("\"", 169)
            
            #line 5 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 159), Tuple.Create<System.Object, System.Int32>(Model.Seq
            
            #line default
            #line hidden
, 159), false)
);

WriteLiteral(" data-model-property=\"key\"");

WriteAttribute("name", Tuple.Create(" name=\"", 196), Tuple.Create("\"", 253)
            
            #line 5 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                          , Tuple.Create(Tuple.Create("", 203), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 203), false)
, Tuple.Create(Tuple.Create("", 249), Tuple.Create(".Seq", 249), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"SeqGrupoCurricular\"");

WriteAttribute("value", Tuple.Create(" value=\"", 326), Tuple.Create("\"", 359)
            
            #line 6 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 334), Tuple.Create<System.Object, System.Int32>(Model.SeqGrupoCurricular
            
            #line default
            #line hidden
, 334), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 360), Tuple.Create("\"", 432)
            
            #line 6 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                              , Tuple.Create(Tuple.Create("", 367), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 367), false)
, Tuple.Create(Tuple.Create("", 413), Tuple.Create(".SeqGrupoCurricular", 413), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"SeqGrupoComponenteCurricular\"");

WriteAttribute("value", Tuple.Create(" value=\"", 515), Tuple.Create("\"", 558)
            
            #line 7 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
      , Tuple.Create(Tuple.Create("", 523), Tuple.Create<System.Object, System.Int32>(Model.SeqGrupoComponenteCurricular
            
            #line default
            #line hidden
, 523), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 559), Tuple.Create("\"", 641)
            
            #line 7 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 566), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 566), false)
, Tuple.Create(Tuple.Create("", 612), Tuple.Create(".SeqGrupoComponenteCurricular", 612), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"SeqGrupoCurricularSuperior\"");

WriteAttribute("value", Tuple.Create(" value=\"", 722), Tuple.Create("\"", 763)
            
            #line 8 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
    , Tuple.Create(Tuple.Create("", 730), Tuple.Create<System.Object, System.Int32>(Model.SeqGrupoCurricularSuperior
            
            #line default
            #line hidden
, 730), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 764), Tuple.Create("\"", 844)
            
            #line 8 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                              , Tuple.Create(Tuple.Create("", 771), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 771), false)
, Tuple.Create(Tuple.Create("", 817), Tuple.Create(".SeqGrupoCurricularSuperior", 817), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"SeqPai\"");

WriteAttribute("value", Tuple.Create(" value=\"", 905), Tuple.Create("\"", 926)
            
            #line 9 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>(Model.SeqPai
            
            #line default
            #line hidden
, 913), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 927), Tuple.Create("\"", 987)
            
            #line 9 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
      , Tuple.Create(Tuple.Create("", 934), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 934), false)
, Tuple.Create(Tuple.Create("", 980), Tuple.Create(".SeqPai", 980), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Descricao\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1051), Tuple.Create("\"", 1075)
            
            #line 10 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 1059), Tuple.Create<System.Object, System.Int32>(Model.Descricao
            
            #line default
            #line hidden
, 1059), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1076), Tuple.Create("\"", 1139)
            
            #line 10 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
           , Tuple.Create(Tuple.Create("", 1083), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 1083), false)
, Tuple.Create(Tuple.Create("", 1129), Tuple.Create(".Descricao", 1129), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"TipoConfiguracaoDescricao\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1219), Tuple.Create("\"", 1259)
            
            #line 11 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
  , Tuple.Create(Tuple.Create("", 1227), Tuple.Create<System.Object, System.Int32>(Model.TipoConfiguracaoDescricao
            
            #line default
            #line hidden
, 1227), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1260), Tuple.Create("\"", 1339)
            
            #line 11 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                           , Tuple.Create(Tuple.Create("", 1267), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 1267), false)
, Tuple.Create(Tuple.Create("", 1313), Tuple.Create(".TipoConfiguracaoDescricao", 1313), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"FormatoConfiguracaoGrupo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1418), Tuple.Create("\"", 1457)
            
            #line 12 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
 , Tuple.Create(Tuple.Create("", 1426), Tuple.Create<System.Object, System.Int32>(Model.FormatoConfiguracaoGrupo
            
            #line default
            #line hidden
, 1426), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1458), Tuple.Create("\"", 1536)
            
            #line 12 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                         , Tuple.Create(Tuple.Create("", 1465), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 1465), false)
, Tuple.Create(Tuple.Create("", 1511), Tuple.Create(".FormatoConfiguracaoGrupo", 1511), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"QuantidadeItens\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1606), Tuple.Create("\"", 1636)
            
            #line 13 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 1614), Tuple.Create<System.Object, System.Int32>(Model.QuantidadeItens
            
            #line default
            #line hidden
, 1614), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1637), Tuple.Create("\"", 1706)
            
            #line 13 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                       , Tuple.Create(Tuple.Create("", 1644), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 1644), false)
, Tuple.Create(Tuple.Create("", 1690), Tuple.Create(".QuantidadeItens", 1690), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"QuantidadeHoraAula\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1779), Tuple.Create("\"", 1812)
            
            #line 14 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 1787), Tuple.Create<System.Object, System.Int32>(Model.QuantidadeHoraAula
            
            #line default
            #line hidden
, 1787), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1813), Tuple.Create("\"", 1885)
            
            #line 14 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                             , Tuple.Create(Tuple.Create("", 1820), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 1820), false)
, Tuple.Create(Tuple.Create("", 1866), Tuple.Create(".QuantidadeHoraAula", 1866), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"QuantidadeHoraRelogio\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1961), Tuple.Create("\"", 1997)
            
            #line 15 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 1969), Tuple.Create<System.Object, System.Int32>(Model.QuantidadeHoraRelogio
            
            #line default
            #line hidden
, 1969), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1998), Tuple.Create("\"", 2073)
            
            #line 15 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2005), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2005), false)
, Tuple.Create(Tuple.Create("", 2051), Tuple.Create(".QuantidadeHoraRelogio", 2051), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"QuantidadeCreditos\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2146), Tuple.Create("\"", 2179)
            
            #line 16 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2154), Tuple.Create<System.Object, System.Int32>(Model.QuantidadeCreditos
            
            #line default
            #line hidden
, 2154), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 2180), Tuple.Create("\"", 2252)
            
            #line 16 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                             , Tuple.Create(Tuple.Create("", 2187), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2187), false)
, Tuple.Create(Tuple.Create("", 2233), Tuple.Create(".QuantidadeCreditos", 2233), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"DescricaoFormatada\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2325), Tuple.Create("\"", 2358)
            
            #line 17 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2333), Tuple.Create<System.Object, System.Int32>(Model.DescricaoFormatada
            
            #line default
            #line hidden
, 2333), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 2359), Tuple.Create("\"", 2431)
            
            #line 17 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                             , Tuple.Create(Tuple.Create("", 2366), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2366), false)
, Tuple.Create(Tuple.Create("", 2412), Tuple.Create(".DescricaoFormatada", 2412), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"ContemGrupos\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2498), Tuple.Create("\"", 2525)
            
            #line 18 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2506), Tuple.Create<System.Object, System.Int32>(Model.ContemGrupos
            
            #line default
            #line hidden
, 2506), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 2526), Tuple.Create("\"", 2592)
            
            #line 18 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                 , Tuple.Create(Tuple.Create("", 2533), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2533), false)
, Tuple.Create(Tuple.Create("", 2579), Tuple.Create(".ContemGrupos", 2579), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"ContemComponentes\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2664), Tuple.Create("\"", 2696)
            
            #line 19 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2672), Tuple.Create<System.Object, System.Int32>(Model.ContemComponentes
            
            #line default
            #line hidden
, 2672), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 2697), Tuple.Create("\"", 2768)
            
            #line 19 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                           , Tuple.Create(Tuple.Create("", 2704), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2704), false)
, Tuple.Create(Tuple.Create("", 2750), Tuple.Create(".ContemComponentes", 2750), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Codigo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2829), Tuple.Create("\"", 2850)
            
            #line 20 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2837), Tuple.Create<System.Object, System.Int32>(Model.Codigo
            
            #line default
            #line hidden
, 2837), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 2851), Tuple.Create("\"", 2911)
            
            #line 20 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
     , Tuple.Create(Tuple.Create("", 2858), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 2858), false)
, Tuple.Create(Tuple.Create("", 2904), Tuple.Create(".Codigo", 2904), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"CargaHoraria\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2978), Tuple.Create("\"", 3005)
            
            #line 21 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 2986), Tuple.Create<System.Object, System.Int32>(Model.CargaHoraria
            
            #line default
            #line hidden
, 2986), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 3006), Tuple.Create("\"", 3072)
            
            #line 21 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                 , Tuple.Create(Tuple.Create("", 3013), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 3013), false)
, Tuple.Create(Tuple.Create("", 3059), Tuple.Create(".CargaHoraria", 3059), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Formato\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3134), Tuple.Create("\"", 3156)
            
            #line 22 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 3142), Tuple.Create<System.Object, System.Int32>(Model.Formato
            
            #line default
            #line hidden
, 3142), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 3157), Tuple.Create("\"", 3218)
            
            #line 22 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
       , Tuple.Create(Tuple.Create("", 3164), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 3164), false)
, Tuple.Create(Tuple.Create("", 3210), Tuple.Create(".Formato", 3210), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Credito\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3280), Tuple.Create("\"", 3302)
            
            #line 23 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 3288), Tuple.Create<System.Object, System.Int32>(Model.Credito
            
            #line default
            #line hidden
, 3288), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 3303), Tuple.Create("\"", 3364)
            
            #line 23 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
       , Tuple.Create(Tuple.Create("", 3310), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 3310), false)
, Tuple.Create(Tuple.Create("", 3356), Tuple.Create(".Credito", 3356), true)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-lookup-component=\"Folha\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3424), Tuple.Create("\"", 3444)
            
            #line 24 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
, Tuple.Create(Tuple.Create("", 3432), Tuple.Create<System.Object, System.Int32>(Model.Folha
            
            #line default
            #line hidden
, 3432), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 3445), Tuple.Create("\"", 3504)
            
            #line 24 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
   , Tuple.Create(Tuple.Create("", 3452), Tuple.Create<System.Object, System.Int32>(SMCLookupHelper.GetCurrentPropertyName(Smc)
            
            #line default
            #line hidden
, 3452), false)
, Tuple.Create(Tuple.Create("", 3498), Tuple.Create(".Folha", 3498), true)
);

WriteLiteral(" />\r\n\r\n");

            
            #line 26 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
	
            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
     if (Model.Seq != 0)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"smc-sga-valor-selecionado\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
             if (!string.IsNullOrEmpty(Model.DescricaoGrupoCurricular))
            {
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
           Write(Smc.Instructions().Text(Model.DescricaoGrupoCurricular));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
                                                                        
            }

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 33 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
          Write(Model.DescricaoFormatada);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t</div>\r\n");

            
            #line 35 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
	}
	else
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"smc-sga-valor-selecionado\"");

WriteLiteral(">\r\n\t\t\t<p");

WriteLiteral(" class=\"smc-sga-valor-selecionado-pesquisa\"");

WriteLiteral(">Pesquisar...</p>\r\n\t\t</div>\r\n");

            
            #line 41 "..\..\Areas\CUR\Lookups\LK_CUR_008_Grupo_Componente_Curricular\Views\_ValoresSelecionadosLookup.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
