//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.SGA.Administrativo.Areas.FIN.Views.InstituicaoNivelBeneficio.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.SGA.Administrativo.Areas.FIN.Views.InstituicaoNivelBeneficio.App_LocalResourc" +
                            "es.MetadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        internal static string DataFimValidade {
            get {
                return ResourceManager.GetString("DataFimValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        internal static string DataInicioValidade {
            get {
                return ResourceManager.GetString("DataInicioValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefício.
        /// </summary>
        internal static string DescricaoBeneficio {
            get {
                return ResourceManager.GetString("DescricaoBeneficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de dedução.
        /// </summary>
        internal static string FormaDeducao {
            get {
                return ResourceManager.GetString("FormaDeducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclui desbloqueio temporário?.
        /// </summary>
        internal static string IncluirDesbloqueioTemporario {
            get {
                return ResourceManager.GetString("IncluirDesbloqueioTemporario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de benefício.
        /// </summary>
        internal static string InstituicaoNivelBeneficioDynamicModel {
            get {
                return ResourceManager.GetString("InstituicaoNivelBeneficioDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº padrão de parcelas.
        /// </summary>
        internal static string NumeroParcelasPadraoCondicaoPagamento {
            get {
                return ResourceManager.GetString("NumeroParcelasPadraoCondicaoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório adesão ao contrato?.
        /// </summary>
        internal static string ObrigatorioAdesaoContrato {
            get {
                return ResourceManager.GetString("ObrigatorioAdesaoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório condição de pagamento?.
        /// </summary>
        internal static string ObrigatorioCondicaoPagamento {
            get {
                return ResourceManager.GetString("ObrigatorioCondicaoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefício.
        /// </summary>
        internal static string SeqBeneficio {
            get {
                return ResourceManager.GetString("SeqBeneficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dedução.
        /// </summary>
        internal static string TipoDeducao {
            get {
                return ResourceManager.GetString("TipoDeducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string ValorAuxilio {
            get {
                return ResourceManager.GetString("ValorAuxilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor / percentual.
        /// </summary>
        internal static string ValorDeducao {
            get {
                return ResourceManager.GetString("ValorDeducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor / percentual.
        /// </summary>
        internal static string ValorDeducaoMoeda {
            get {
                return ResourceManager.GetString("ValorDeducaoMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor / percentual %.
        /// </summary>
        internal static string ValorDeducaoPercentual {
            get {
                return ResourceManager.GetString("ValorDeducaoPercentual", resourceCulture);
            }
        }
    }
}
